---
title: "Giardiniera"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Pickling and Fermenting"]
---

**Ingredients:** *2 quart yield*

-   4 serrano chiles, thinly sliced, with seeds removed

-   2 red sweet peppers, cut into ½-inch pieces

-   1 or 2 celery ribs, sliced or julienned

-   1 or 2 carrots, sliced or julienned

-   1 medium head cauliflower, cut into small florets

-   ½ cup salt

-   2 cloves garlic, slivered

-   3 teaspoons dried oregano

-   1 teaspoon red pepper flakes

-   ½ teaspoon celery seeds

-   1 teaspoon crushed black peppercorns

-   1 cup white vinegar

-   ½ cup olive oil (not extra virgin)

-   ½ cup grapeseed or safflower oil

**Directions:**

1.  In a large bowl, using your hands, mix the vegetables and salt until
    well combined. Cover the vegetables with water. Cover the bowl and
    allow the mixture to sit, unrefrigerated, for 8 to 12 hours.

2.  Drain the vegetables and rinse thoroughly. Sterilize 2 quart-size
    glass jars, with lids, in the dishwasher or by submerging them in
    boiling water for 10 minutes.

3.  In one sterilized jar, combine the garlic and all the herbs and
    spices; add the vinegar and oil and shake well to emulsify the
    dressing. Pour half the dressing into the other jar.

4.  Pack the vegetables into the jars. If vegetables are not completely
    coated, make and add more dressing. Screw lids onto jars and
    refrigerate. Allow the mixture to mellow for a couple of days before
    serving.
