---
title: "Pickled Coleslaw"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Pickling and Fermenting"]
---

**Ingredients:**

-   1 head cabbage, green or purple -- shredded

-   2 Tb canning & pickling salt

-   3 whole carrots, peeled and finely shredded

-   2 c water

-   2 ½ c white distilled vinegar

-   2 ⅓ c [[granulated
    sugar]{.underline}](https://www.amazon.com/Wholesome-Organic-Sugar-Trade-single/dp/B006CVNF2G?crid=2KXK5G2C54DGQ&dib=eyJ2IjoiMSJ9.6Mw6CQf8EFgxfMoA9G-4pFd4kbyHVKxnOqBM7pnCamezYUPTFXxVY3ORXfqlgeA1qSPOnZq4X_j014a2b3ngWx_hrt6wRes5A-KKwE3HgSLlO3PPNUhGi0vWsVIV7f1MRYePChyZTVKowJJaQIJeniTnhjjYsSRB-P-hweCjOs7MDuezX-YyL3AANlKzbn7G84HKuK9dZtMWzhgDL53K6QyZBvwBJNTBaziQ493rWQHpNaKua1_1cq0rXYEchXe9kiXkBNWNxWsA3xW3POEssoVGg2sM5vnpiRXcBA_PVrw.PiFp42zKU1S9XvRzL2Qm0y8bD80RUS3Yq4VruIQY8BM&dib_tag=se&keywords=granulated+sugar&qid=1711406133&s=grocery&sprefix=granul%2Cgrocery%2C113&sr=1-1-spons&sp_csd=d2lkZ2V0TmFtZT1zcF9hdGY&psc=1&linkCode=ll1&tag=constancesmit-20&linkId=b208b41b03142956aeecfb78daa9c0aa&language=en_US&ref_=as_li_ss_tl)

-   4 pinches celery seed

-   ½ teaspoon pickle crisp

**Directions:**

1.  Combine the shredded/thinly sliced cabbage in a large bowl with the
    canning salt. Toss the cabbage to mix the salt all through it. Cover
    the bowl with a tea towel and set it aside for 2 -- 4 hours.

2.  Place cabbage in a colander and rinse with cold water to remove as
    much of the salt as possible. Work in batches, then let the cabbage
    rest in the colander a few minutes while you prepare the brine.

3.  Combine the water, vinegar, and sugar in a large, nonreactive pot.
    Bring the mixture to a boil and let it boil for 1 minute. Reduce the
    heat to keep the brine nice and hot while you do the next step.

4.  Put the shredded cabbage in a large bowl and add the shredded
    carrots. Mix them together.

5.  Pack the cabbage and carrot mixture into your jars, leaving 1/2 inch
    of head space.

6.  To each jar add a pinch of celery seed and 1/8 teaspoon of pickle
    crisp.

7.  Ladle in the brine.

8.  Close the jars and ferment.

**Source:**
[[https://cosmopolitancornbread.com/pickled-coleslaw/]{.underline}](https://cosmopolitancornbread.com/pickled-coleslaw/)
