---
title: "Burrito Bowls"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Mexican"]
---

**Ingredients:**

[FOR THE CHICKEN THIGHS]{.underline}

-   2½ lbs (1135 g) boneless skinless chicken thighs

-   1 tbsp (15 g) oil

-   2 tsp (6 g) paprika

-   2 tsp (6 g) cumin

-   2 tsp (6 g) onion powder

-   2 tsp (6 g) garlic powder

-   2 tsp (6 6) ancho chili powder

-   1 tsp (6 g) salt

-   2 tbsp (30 g) lime juice

-   2 tbsp (30 g) orange juice

[FOR THE RICE AND BEANS]{.underline}

-   5 cups (750 g) cooked rice

-   2 cans (880 g) pinto beans

-   ½ bunch (30 g) cilantro

-   2 tbsp (30 g) lime juice

-   1 tbsp (15 g) oil

-   Salt and pepper to taste

[FOR THE BOWLS]{.underline}

-   3 medium (500 g) russet potatoes

-   2 medium (300 g) bell peppers any color

-   1 medium (200 g) onion

-   2 tbsp (30 g) oil

-   1 tbsp (15 g) lime juice

-   10 tbsp (70 g) shredded monterey cheese

-   1¼ cups (300 g) salsa buy your favorite jar

-   10 tbsp (150 g) sour cream

**Directions:**

[FOR THE RICE]{.underline}

Cook enough rice to yield 5 or 750g of cooked rice. 1 cup of dry rice
will make between 2-3 cups of cooked rice depending on what kind you
use.

[FOR THE CHICKEN]{.underline}

1.  Preheat your oven to 425°F (218°C).

2.  In a large bowl make the marinade by mixing together 1 tbsp of oil,
    orange juice, and lime juice and all of the seasonings. Reserve a
    couple of spoonfuls of the marinade and set aside.

3.  Add in the chicken and coat all of the surfaces. If you want to
    allow the chicken to marinate, give it an hour or two. I just roast
    it right away.

4.  Line a large sheet pan with foil and spray it with oil. Place the
    chicken thighs on the sheet pan with the smooth side facing down.
    Roast for 12-14 minutes. While the chicken is cooking, scroll down
    to the vegetable section working on the rest of the prep.

5.  After your chicken timer is up, remove it from the oven and chop it
    into a large dice then return to the sheet pan. It is okay if it
    isn\'t cooked all of the way through, it is going back into the
    oven.

6.  Mix in the remaining marinade that your reserved and stir it into
    the chopped chicken. Spread it out across the pan so that it is
    evenly space and return to the oven on the top shelf and change the
    oven to broil.

7.  Broil for 5-8 minutes or until the chicken has browned to your
    liking. After a couple of minutes you can remove the pan and stir
    the chicken for even browning. Keep a close eye on it as it will be
    prone to burning under the broiler.

[FOR THE VEGETABLES]{.underline}

1.  Wash and cut your potatoes into a large dice.

2.  Toss the diced potatoes with 1 tbsp of oil and salt and pepper in a
    large bowl.

3.  I cook the potatoes in the air fryer at 400°F (204°C) for 15
    minutes. You can also throw them in the oven with the chicken but it
    will likely take a bit longer.

4.  Cut the bell peppers and onion into thin slices.

5.  Roughly chop the cilantro into small pieces.

6.  To cook the peppers and onions, heat a large skillet over medium
    high heat and add 1 tbsp of oil.

7.  Dump in the peppers and onions and season lightly with salt. Allow
    the vegetables to develop a bit of color first, then drizzle over a
    tablespoon or two of water and cover to steam for 1-2 minutes or
    until they have begun to soften.

8.  Once the peppers and onions have cooked, add 1 tbsp of lime juice
    and season with salt to taste.

9.  FOR THE RICE AND BEANS

10. In a large bowl, add 5 cups (750g) of cooked rice, and two cans of
    beans that you drain and rinsed first.

11. Add 1 tbsp oil, 2 tbsp lime juice, ¼ cup (20g) of chopped cilantro
    and salt and pepper to taste.

[PLATING]{.underline}

-   This recipe makes 5 servings. Divide your ingredients evenly 5 ways.
    Create a base layer of rice and beans, add a potato layer next, then
    the peppers and onions, and top with chicken.

-   Each dish gets ¼ cup of salsa and 2 tbsp of shredded cheese on top.
    Measure out the salsa into small ramekins and add to the dishes.
    After reheating you will also top with 2 tbsp of sour cream.

-   These will last for up to 5 days in the fridge.
