---
title: "Olive Tapenade Slab Sandwich"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Sandwiches"]
---

**Ingredients:**

[For the roasted red peppers:]{.underline}

-   6 red bell peppers, halved and seeded

[For the whipped goat cheese:]{.underline}

-   8-oz goat cheese

-   1 tablespoon honey

-   ¼ cup milk, plus more as needed

[For assembly:]{.underline}

-   1 recipe overnight focaccia

-   ¼ cup whipped goat cheese, plus more to taste

-   6 roasted red peppers, or more or less to taste

-   1/4 cup olive tapenade, plus more to taste

-   2 to 4 ounces mixed greens or arugula

**Directions:**

1.  Preheat the oven to 425ºF. Line a rimmed sheet pan with parchment
    paper (for easy clean up --- make sure it extends over the edges).
    Place peppers cut-side down on parchment paper. (Alternatively, rub
    a small amount of olive oil on the sheet tray.) Place pan in the
    oven for about 30 to 40 minutes, until the skin is blistery and
    charred. Don't be impatient here: If the skin isn't blistery enough,
    the peppers will be difficult to peel.

2.  Place the peppers in a large bowl and cover with a cloth bowl cover
    or plastic wrap. Let sit for at least 20 minutes and up to 4 or 5
    hours (or longer.) When cool enough to handle, remove the skin and
    discard.

3.  Meanwhile, make the whipped goat cheese: place the goat cheese,
    honey, and milk in a food processor. Purée until smooth, adding more
    milk as needed to reach a creamy, spreadable consistency.

4.  Assemble the slab sandwiches: Use a serrated knife to halve each
    focaccia round in half crosswise. Spread the tapenade over one
    bottom half of each pair of bread rounds. Spread the whipped goat
    cheese over one top half of each pair. Top the tapenade with a layer
    of roasted red peppers. Pile greens or arugula over top. Close the
    sandwich. Present the assembled slab on a large board and cut into
    individual sandwiches just before serving.
