---
title: "Sushi Rice"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Japan"]
---

**Ingredients:**

-   2 cups uncooked sushi rice

-   2 cups water

-   ¼ cup rice wine vinegar or to taste

-   ¼ cup white sugar or to taste

-   1 tablespoon vegetable oil

-   1 teaspoon salt or to taste

**Directions:**

1.  Gather ingredients.

2.  Rinse rice under cold water in a strainer until water runs clear.

3.  Combine rice and water in a saucepan over medium-high heat; bring to
    a boil. Reduce heat to low, cover, and cook for 12 minutes. Remove
    from heat; let stand, covered, until tender, 10 minutes more. The
    rice will continue to steam. Remove lid; let rice cool.

4.  Meanwhile, combine rice wine vinegar, sugar, oil, and salt in a
    small saucepan over medium heat; cook until sugar has dissolved.
    Allow to cool.

5.  Stir vinegar mixture into rice. It may look wet at first, but keep
    stirring; rice will dry as it cools.

6.  Enjoy!

**Source:**
[[https://www.allrecipes.com/recipe/99211/perfect-sushi-rice/]{.underline}](https://www.allrecipes.com/recipe/99211/perfect-sushi-rice/)
