---
title: "Hummus with Spiced Chicken and Cauliflower"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Party Snacks and Dips"]
---

**Ingredients:**

[Hummus]{.underline}

-   2 (15.5-ounce) cans chickpeas, drained, 1/2 cup chickpea liquid
    reserved, divided

-   1/3 cup tahini

-   1/4 cup extra-virgin olive oil

-   3 tablespoons fresh lemon juice

-   1 1/2 teaspoons kosher salt, plus more to taste

-   1 large garlic clove, coarsely chopped

-   Cumin

-   Paprika

[Chicken and Cauliflower]{.underline}

-   1 pound boneless, skinless chicken thighs, cut into 1-inch pieces

-   2 teaspoons ground cumin

-   1 teaspoon smoked paprika

-   1 teaspoon kosher salt, plus more to taste

-   3/4 teaspoon ground coriander

-   1/2 teaspoon ground cinnamon

-   1/4 teaspoon black pepper

-   1/4 cup extra-virgin olive oil, divided, plus more for drizzling

-   1 large yellow onion, thinly sliced

-   1/2 small head cauliflower, cored and cut into small florets (about
    2 1/4 cups)

-   1/3 cup water

-   1/4 cup dried currants

-   Chopped fresh flat-leaf parsley, za'atar, and toasted pine nuts, for
    serving

**Directions:**

[Hummus]{.underline}

1.  Reserve some chickpeas for garnish, let them dry

2.  Process lemon juice and garlic for 10-20 seconds, then let that rest
    for 5-10 minutes.

3.  Process chickpeas, tahini, oil, and salt in a food processor until a
    coarse paste forms, about 20 seconds, stopping to scrape down sides
    as needed.

4.  With processor running, slowly pour 1/4 cup reserved chickpea liquid
    through food chute, and process until mostly smooth and creamy,
    about 1 minute and 30 seconds.

5.  Stop and check the texture, if you want a creamier consistency,
    stream in olive oil. Finally, Add salt to taste. Then, for the best
    consistency, let the hummus rest in the fridge for at least an hour.

[Chicken and Cauliflower]{.underline}

6.  Toss together chicken, cumin, paprika, salt, coriander, cinnamon,
    and pepper in a medium bowl until chicken is well coated. Heat 2
    tablespoons oil in a 10-inch high-sided skillet over medium-high.
    Add chicken in an even layer; cook, undisturbed, until bottom of
    chicken is lightly browned, about 5 minutes. Stir and cook, stirring
    occasionally, until chicken is cooked through, about 4 minutes;
    transfer to a medium bowl. Reduce heat to medium. Add onion and
    remaining 2 tablespoons oil; cook, stirring occasionally with a
    wooden spoon to loosen browned bits, until softened and lightly
    browned, about 15 minutes. Stir in cauliflower, 1/3 cup water, and
    currants; cover and cook, stirring occasionally to loosen onions
    from bottom of pan, until cauliflower is tender and onions are
    caramelized, about 10 minutes. Return chicken to pan, and cook until
    warmed through. Season with salt to taste.

7.  Spread hummus on a large serving platter, making a well in the
    hummus with the back of a spoon. (Alternately, divide hummus among
    individual serving plates, and make a well in each.) Spoon the
    chicken and cauliflower mixture into the well (or individual wells).
    Garnish with parsley, za'atar, and pine nuts. Drizzle with oil.
    Serve immediately.
