---
title: "Olive Tapenade"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Party Snacks and Dips"]
---

**Ingredients:**

-   2 cups pitted black olives, such as Kalamata, see notes above

-   grated zest and juice of ½ to 1 lemon

-   pinch crushed red pepper flakes, optional

-   2 cloves garlic, peeled

-   2 tablespoons capers, drained

-   1 tablespoon white balsamic vinegar

-   2 cups (about) parsley, divided roughly into two 1-cup portions

-   1/3 cup olive oil, plus more to taste

**Directions:**

1.  Pulse the olives, zest, juice of half a lemon, pepper flakes,
    garlic, capers, vinegar, and half of the parsley in the food
    processor until a coarse paste is formed---be sure to pulse to avoid
    turning the purée into complete mush. It may take 20 to 30 quick
    pulses.

2.  Transfer the mixture to a bowl. Finely chop the remaining parsley,
    and stir it in. Stir in the olive oil. Taste; then adjust seasoning
    as necessary with more lemon, pepper flakes, or olive oil. I almost
    always end up using the remaining half lemon, and I always stir in
    more olive oil by the tablespoon until the mixture both looks and
    tastes right.

3.  Store olive tapenade in the refrigerator for 1 week. Bring to room
    temperature before serving. If the parsley looks dull after the
    tapenade has spent a few days in the fridge, spruce it up by adding
    freshly chopped parsley.
