---
title: "Queso Two Ways"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Party Snacks and Dips"]
---

**Ingredients:**

[Traditional:]{.underline}

-   2 Tbsp Neutral Tasting Oil

-   1 Medium Yellow Onion, diced

-   2 Jalapenos, finely diced

-   Salt

-   3 Cloves Garlic, roughly chopped

-   1 Tomato, diced

-   3/4 lb American Cheese, grated

-   1/4 lb Pepper Jack Cheese, grated

-   1 Cup Whole Milk

-   1/4 Cup Cilantro, finely chopped

[Fancy Version:]{.underline}

-   2 Tbsp Unsalted Butter

-   2 Shallots, finely diced

-   4 Serrano Chilis, optionally seeded and sliced

-   3 Cloves Garlic, roughly chopped

-   Salt

-   Pepper

-   2 Tbsp All-Purpose Flour

-   1 Cup Whole Milk

-   4.5 Cups Cheddar Cheese, shredded

-   1 Cup Gruyere Cheese, shredded

-   1/2 Cup Sour Cream

[Garnish:]{.underline}

-   Avocado, diced

-   Flaky Salt

-   Queso

-   Pickled Onions

-   Serrano Chilis, sliced

-   Cilantro

-   Hot Sauce

**Directions:**

[Traditional Method:]{.underline}

1.  In a medium saucepan, add two tablespoons of neutral-tasting oil and
    heat over medium heat until very hot.

2.  Add one medium yellow onion that has been diced, followed by two
    finely diced jalapenos. Season that to taste with salt. Stir and let
    those sweat until softened.

3.  Once softened, add in three cloves of roughly chopped garlic and
    saute for 2-3 minutes or until everything is softened. Stir in one
    diced tomato and saute until the tomato is hot. Then add in ¾
    quarters of a pound of freshly grated American cheese, followed by ¼
    pound of pepper jack cheese and 1 cup of whole milk.

4.  Continue heating over medium heat while stirring constantly until
    silky smooth. Finish with salt to taste and ¼ cup of finely chopped
    cilantro.

[Fancy Method:]{.underline}

5.  Start with 2 ½ tablespoons of unsalted butter in a medium saucepan
    and heat it over medium heat, just until the butter is melted.

6.  Next, add in two finely diced shallots and four serranos that have
    been optionally seeded and sliced. Then add in three cloves of
    roughly chopped garlic and season to taste with salt and freshly
    cracked black pepper.

7.  Stir and cook until all of the vegetables are softened - about 2-3
    minutes.

8.  Sprinkle in 2 tablespoons of all-purpose flour and stir to combine.
    Stir occasionally for about 30 seconds, then whisk in 1 cup of whole
    milk. Keep whisking just until it thickens and forms a bechamel.

9.  In a separate bowl, mix together 4 ½ cups of shredded cheddar cheese
    and 1 cup of shredded gruyere cheese. Whisk that cheese mixture into
    your bechamel a little bit at a time until all of it is
    incorporated. Turn off the heat and continuously whisk until the
    cheese is completely melted and you have a nice smooth consistency.

10. Finally, finish that off with ½ cup of sour cream and whisk
    together. Adjust salt and pepper levels if necessary.

11. To place, slice or dice a ripe avocado and place a generous mound in
    the center of a bowl. Top with flakey salt and your hot queso.
    Garnish with pickled onions, thinly sliced serrano chilies, cilantro
    leaves and a hot sauce of your choice.
