---
title: "Spinach and Artichoke Dip - Weissman"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Party Snacks and Dips"]
---

**Ingredients:**

-   2 Tbsp (14g) unsalted butter

-   4 cloves garlic, finely chopped

-   4 cups (110g) spinach leaves

-   ½ cup (110g) cream cheese, softened

-   ½ cup (100g) crème fraîche

-   ¼ cup (21g) freshly grated Parmigiano Reggiano

-   Kosher salt and pepper, to taste

-   1 cup (150g) roughly chopped, cooked artichoke hearts

-   Cooking spray

-   ⅓ cup (35g) grated low-moisture mozzarella cheese

-   ⅓ cup (33g) Monterey jack cheese

-   Chips, to serve (optional)

**Directions:**

1.  Preheat oven to 375℉ / 190℃.

2.  In a medium sauté pan set over medium heat, melt the butter. Once
    melted, add garlic and sauté until fragrant. Add spinach and cook,
    stirring often, until wilted. Remove from the pan and drain through
    a fine mesh strainer, pushing on the spinach to remove as much
    excess liquid as possible. Remove from the strainer and finely chop
    the spinach.

3.  In a medium bowl, whisk together the cream cheese and crème fraîche
    until combined. Add the parmesan and salt and pepper to taste.

4.  Fold in the artichoke hearts and chopped spinach until combined.

5.  Grease a 3-quart baking dish with cooking spray and spread the
    mixture evenly in the dish.

6.  In a separate bowl, mix together the mozzarella and Monterey jack
    cheese. Sprinkle the cheese on top of the dip. Bake for 20 minutes
    or until the dip is bubbling, the cheese is melted and the top is
    golden brown. Serve as a side dish or with chips.

**Source:**
[[https://www.joshuaweissman.com/recipes/ultimate-spinach-artichoke-dip-recipe#recipe]{.underline}](https://www.joshuaweissman.com/recipes/ultimate-spinach-artichoke-dip-recipe#recipe)
