---
title: "Dan Dan Noodles"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Noodles"]
---

**Ingredients:**

*Sauce:*

-   1/3 cup Chinese sesame paste (or unsweetened natural peanut butter)

-   1/3 cup light soy sauce (or soy sauce)

-   1/4 cup Chinkiang vinegar

-   4 cloves garlic , finely minced

-   2 green onion , finely minced

-   2 tablespoons honey (or agave syrup)

-   1/2 to 1 teaspoon Sichuan peppercorns , toasted and grounded

*Pork:*

-   1 tablespoon peanut oil (or vegetable oil)

-   1 lb (450 g) ground pork

-   1 tablespoon minced ginger

-   2 green onions , chopped

-   1 1/2 tablespoons fermented black beans , rinsed and chopped

-   1/2 cup Sui Mi Ya Cai (Sichuan preserved mustard greens)

-   2 tablespoons Shaoxing wine (or dry sherry)

-   1/2 teaspoon sugar

*Assembly:*

-   1/3 cup roasted peanuts , crushed

-   14 oz (400 g) Dan Dan noodles (or thin wheat noodles)

-   1 small batch leafy green vegetables , roughly chopped (spinach,
    choy sum, baby bok choy etc.)

-   Homemade chili oil , to taste

**Directions:**

1.  Prepare sauce

2.  Whisk the sesame paste and light soy sauce together in a bowl until
    fully incorporated. Add the Chinkiang vinegar. Continue stirring
    until mixed. Then mix in the garlic, green onion, honey, and Sichuan
    peppercorns.

3.  Prepare the pork topping

4.  Heat the oil in a large nonstick skillet over medium-high heat until
    hot. Add the pork. Cook and stir until the surface is lightly
    browned.

5.  Turn to medium heat. Add the ginger, green onion, fermented black
    beans, Sui Mi Ya Cai, cooking wine, and sugar. Cook and chop the
    pork into small pieces, until all the liquid has evaporated and the
    pork turns a dark brown color. Transfer to a bowl and set aside.

6.  Prepare the noodles

7.  Cook the noodles according to instructions.

8.  Briefly blanch the leafy green vegetables, drain, and set aside.

9.  To assemble the noodle bowls

10. For each noodle bowl, add 1/4 cup of noodle sauce. Add the chili oil
    according to your taste. Add some noodles, then top with a few
    spoonfuls of the cooked pork and green veggies. Garnish with peanut
    crumbles and chopped green onion. Sprinkle with a pinch of toasted
    ground Sichuan peppercorn, if you like the numbing taste.

11. Serve hot or cold.

12. 
