---
title: "Lo Mein"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Noodles"]
---

**Ingredients:**

*Noodles*:

-   1.5 tbsp vegetable or peanut oil

-   2 garlic cloves , finely minced (Note 1)

-   1/2 onion , finely sliced

-   300g / 10oz chicken or other protein , sliced 0.5cm / 1/5\" thick
    (Note 2)

-   2 medium carrots , peeled and cut into 4 x 0.75cm / 1.75 x 1/3\"
    batons

-   1 large red capsicum / bell pepper , sliced (or 2 small)

-   6 green onions , cut into 5 cm/2" lengths

-   500g / 1lb Lo Mein, Hokkien or other medium thickness egg noodles,
    fresh, , prepared per packet (Note 3 for dried)

-   1/4 cup (65ml) water

    -   Only needed if using actual Lo Mein noodles and cooked the same
        way as the directions for this specific recipe

*Sauce*:

-   4 tsp cornflour / cornstarch

-   2 tbsp dark soy sauce (Note 4)

-   2 tbsp soy sauce or light soy sauce (Note 4)

-   1 tbsp Chinese cooking wine or Mirin (Note 5 subs)

-   1 tsp white sugar (omit if using Mirin)

-   1/2 tsp sesame oil , toasted, optional (Note 6)

-   1/4 tsp white pepper (sub black)

**Directions:**

1.  Sauce: Mix cornflour and dark soy until lump free, then add
    remaining Sauce ingredients.

2.  Season Chicken: Transfer 2 tsp Sauce into bowl with chicken. Toss to
    coat.

3.  Heat oil in a wok or large heavy based skillet over high heat until
    smoking.

4.  Add onion and garlic, stir 30 seconds.

5.  Add chicken, stir until white on the outside, still raw inside - 1
    minute.

6.  Add carrot and capsicum/bell peppers, cook 2 minutes or until
    chicken is cooked.

7.  Add noodles, Sauce and water. Use 2 wooden spoons and toss for 30
    seconds.

    a.  If not using Lo Mein noodles, and subbing with Ramen or another
        kind, cook them in boiling water (like most noodles) and then
        add them to the pan once cooked

8.  Add green onions, toss for another 1 minute until all the noodles
    are slick with sauce.

9.  Serve immediately, garnished with extra green onions if using.
