---
title: "Zhajiang Mian"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Noodles"]
---

**Ingredients:**

-   6 oz. ground pork

-   (170g)

-   ¼ teaspoon salt

-   1 teaspoon cornstarch

-   ½ teaspoon oil (plus 1 tablespoon)

-   1/8 teaspoon white pepper

-   1 oz. pork fat (finely minced; optional)

-   3 slices ginger (minced finely)

-   4 cloves garlic (minced)

-   6 fresh shiitake mushrooms (finely chopped)

-   2 tablespoons sweet bean sauce

-   3 tablespoons ground bean sauce

-   1 tablespoon dark soy sauce

-   1 cup water

-   8 oz. dried wheat noodles (or 1 pound fresh wheat noodles)

-   1 cup carrots (julienned)

-   1 cup cucumbers (julienned)

-   1/2 cup scallions (julienned)

**Directions:**

1.  Marinate the pork with the following for 15 minutes: ¼ teaspoon
    salt, 1 teaspoon cornstarch, ½ teaspoon oil, 1/8 teaspoon white
    pepper.

2.  Heat a tablespoon oil in your wok over medium heat and add the pork
    fat (if using). Cook for 1 minute to render the fat down, and add
    the marinated ground pork to the wok. Cook for a minute to brown it,
    and then add the ginger, garlic, and mushrooms. Stir fry everything
    together for another 2-3 minutes.

3.  Add the sweet bean sauce, ground bean sauce, dark soy sauce, and
    water, stirring everything together well. Lower the heat and cover
    the wok. Simmer the sauce for 15-20 minutes, stirring occasionally
    to prevent sticking.

4.  While that's happening, cook the noodles according to the package
    directions. Mix with the sauce and toss with the julienned carrots,
    cucumbers, and scallions. This amount of sauce should be good for 4
    servings.

**Notes**:

-   Used Doubanjiang instead of the Sweet Bean and Ground Bean Paste

    -   Gave a nice spicy flavor, going a little lighter on overall
        water/liquid is probably for the best

**Nutrition:**

Calories: 446kcal (22%)

Carbohydrates: 52g (17%)

Protein: 19g (38%)

Fat: 19g (29%)

Saturated Fat: 6g (30%)

Cholesterol: 37mg (12%)

Potassium: 390mg (11%)

Fiber: 6g (24%)

Sugar: 11g (12%)

Vitamin A: 5495IU (110%)

Vitamin C: 6.8mg (8%)

Calcium: 36mg (4%)

Iron: 1.3mg (7%)
