---
title: "Greek Honey Garlic Chicken Paidakia"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Chicken"]
aliases:
  - "/pages/recipes/Chicken/Greek Honey Garlic Chicken Paidakia.html"
---
<!-- cm:video:start -->
{{< video https://www.youtube.com/watch?v=mbBz9xrda3c >}}

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "Recipe",
  "cookTime": "PT45M",
  "name": "Greek Honey Garlic Chicken",
  "prepTime": "PT5M",
  "recipeCuisine": "Greek",
  "recipeIngredient": [
    "3lbs chicken thighs (or you can use an entire chicken broken down)",
    "1 red onion sliced",
    "5-6 cloves of garlic in quarters",
    "Salt to taste",
    "Pepper",
    "Thyme",
    "Oregano",
    "Papirka",
    "Bay Leaves",
    "Turmeric",
    "\u00bd cup of honey",
    "Lemon juice from a whole lemon",
    "3 tbsp mustard",
    "Olive oil"
  ],
  "recipeYield": "4",
  "video": {
    "@type": "VideoObject",
    "contentUrl": "https://www.youtube.com/watch?v=mbBz9xrda3c",
    "embedUrl": "https://www.youtube.com/embed/mbBz9xrda3c",
    "name": "Greek Honey Garlic Chicken"
  }
}
</script>
<!-- cm:video:end -->

**Ingredients:**

-   3lbs chicken thighs (or you can use an entire chicken broken down)

-   1 red onion sliced

-   5-6 cloves of garlic in quarters

-   Salt to taste

-   Pepper

-   Thyme

-   Oregano

-   Papirka

-   Bay Leaves

-   Turmeric

-   ½ cup of honey

-   Lemon juice from a whole lemon

-   3 tbsp mustard

-   Olive oil

**Directions:**

1.  Preheat the oven to 400°F. Add everything into a dutch oven or
    roasting pot. Mix the ingredients well and then coat all sides of
    the chicken.

2.  Cover and bake at 400°F for 45-60 minutes. Then remove and serve
    over rice or a salad.
