---
title: "Adobo Sauce"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Sauces and Condiments"]
---

**Ingredients:**

-   Adobo Sauce Ingredients

-   4 guajillo peppers

-   4 ancho peppers

-   3 cups hot water (or enough to cover the dried peppers) + ½ cup

-   1 tablespoon olive oil

-   1/2 small onion, chopped

-   4 cloves garlic, chopped

-   2 tablespoons tomato paste (optional for a milder flavor)

-   ½ teaspoon Mexican cinnamon (or use cinnamon)

-   ½ teaspoon cumin

-   ½ teaspoon Mexican oregano (or use oregano)

-   ½ teaspoon sugar (optional, to taste -- see my NOTES on Optional
    Spices)

-   Salt to taste

**Directions:**

1.  First, remove the stems from the guajillo and ancho peppers and
    remove the seeds. You may need to cut into the peppers for this,
    which is fine.

2.  Heat a large pan to medium heat and dry toast the dried peppers a
    couple minutes per side. They will become more pliable and slightly
    puff up. When you dry toast them in a skillet over medium heat or
    medium-high heat, it helps to release the oils from the pods for
    more flavor.

3.  Place the dried chiles in a large bowl and cover with very hot or
    boiling water. Soak them for 15 minutes, or until they become very
    soft and rehydrate. They could take 20 minutes to 30 minutes to get
    very soft. Transfer the softened peppers to a food processor, but
    reserve the soaking liquid.

4.  While the peppers are softening, cook down the other ingredients.
    Heat 1 tablespoon of olive oil in a medium pan and add the onion.
    Cook it down for 4-5 minutes to soften. Add the garlic and cook for
    another 30 seconds to 1 minute, until it becomes fragrant.

5.  Add the tomato paste, cinnamon, cumin, oregano, sugar and salt. Cook
    for 1 minute, stirring, then stir in 1/2 cup water. Reduce heat and
    simmer for 5 minutes.

6.  Add the mixture to a food processor along with the softened peppers
    and 1/4 to 1/2 cup of fresh water, or you can use the dark liquid
    from soaking the peppers. Process until smooth.

7.  Adjust with salt and sugar to taste, and with a bit more water until
    you achieve your desired consistency. Strain if you'd like a thinner
    sauce, or use as-is.

> **Makes about 2 cups of adobo sauce.**
>
> Store in the refrigerator in an airtight container. **It should last
> about a month this way.**

**Source:**
[[https://www.chilipeppermadness.com/recipes/adobo-sauce/#wprm-recipe-container-18568]{.underline}](https://www.chilipeppermadness.com/recipes/adobo-sauce/#wprm-recipe-container-18568)
