---
title: "Carolina Reaper Hot Sauce"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Sauces and Condiments"]
---

**Ingredients:**

-   8 ounces Carolina Reaper peppers stems removed - NOTE: go by weight,
    not size. This was about 20 pods for me, but mine were small this
    year

-   1 large bulb of garlic top sliced open to expose most of the garlic

-   1 medium white onion sliced in half

-   3 tablespoons good quality vinegar distilled white, champagne or
    apple cider vinegar for more tangy

-   ½ teaspoon salt or more to taste

-   1 cup of water or more, as desired

**Directions:**

1.  Heat your oven to 400 degrees. Set the Carolina Reaper peppers,
    garlic and onion on a baking sheet and bake them about 15-20
    minutes, or until the skins slightly char. Keep an eye on these. You
    don\'t want them to burn, and watch out for any fumes.

2.  Add the peppers and onion to a food processor. Squeeze garlic out of
    their skins and into the food processor they go.

3.  Add in the vinegar and salt. Process until you get a chunky mixture.
    Watch out for the fumes!

4.  Add in a half cup of water and process again until the sauce starts
    to smooth out. Check it for thickness. If you'd like a thinner
    sauce, add in a bit more water a little at a time, processing, until
    you reach your desired consistency.

5.  If desired, you can strain the sauce to smooth it out, or use it
    as-is. If you do strain it, you can discard the pulp or dehydrate it
    to make a superhot seasoning powder.

6.  Pour into sterilized bottles and enjoy. The longer you let it sit,
    the more the flavors will meld.
