---
title: "Chili Oil_Crisps"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Sauces and Condiments"]
---

[Main Ingredients]{.mark}

-   [1.5 oz **Sichuan dried chili flakes**
    ([[Amazon]{.underline}](https://amzn.to/3RUaYGk))]{.mark}

-   [0.50 oz **ginger** (fresh)]{.mark}

-   [1 oz **red onion**]{.mark}

-   [1 oz **shallot**]{.mark}

-   [3 clove **garlic**]{.mark}

-   [2 piece **star anise**]{.mark}

-   [1 dash **sesame seeds** (to taste)]{.mark}

-   [4 oz **neutral oil** (may need an extra tbsp or so if oil
    overheats; good options include corn oil, canola oil, and peanut
    oil)]{.mark}

-   [1 tsp **sesame oil**]{.mark}

[Chili Mix]{.mark}

-   [0.50 tsp **salt**]{.mark}

-   [0.50 tsp **sugar**]{.mark}

-   [0.50 tsp **white pepper**]{.mark}

-   [1 tbsp **paprika** (for color)]{.mark}

-   [1 tbsp **neutral oil**]{.mark}

[Steps:]{.mark}

[First, we\'ll create a flavorful chili mix as the seasoning base for
the chili oil. In a medium, heat-safe bowl, mix together **chili
flakes** (1.5 oz), **salt** (0.50 tsp), **sugar** (0.50 tsp), and
**white pepper** (0.50 tsp).]{.mark}

[To these dry ingredients, add some **oil** (1 tbsp) and mix it in. This
small amount of room temperature oil prevents the dry ingredients from
burning when we pour the hot oil over them later on.]{.mark}

[Optionally, you can add **paprika** (1 tbsp) for a color boost. It
won\'t drastically change the flavor but will help give the chili oil a
nice, bright red color.]{.mark}

[Cut the **ginger** (0.50 oz) and **red onion** (1 oz) into slices.
They\'ll be frying in hot oil, so don\'t fuss over getting them too
paper-thin.]{.mark}

[Smash the **shallot** (1 oz) with the side of your knife, then smash,
peel, and roughly mince the **garlic** (3 clove).]{.mark}

[Smash the **star anise** (2 piece) into smaller pieces, and rinse and
wet the pieces in a bit of cold water. This will help keep them from
burning during the frying step.]{.mark}

[Keep everything separate, but close at hand.]{.mark}

[Heat up your wok over high heat for about 30 seconds, and pour the
**oil** (4 oz) in.]{.mark}

[Once the oil reaches 300°F (150°C), or hot enough to bubble around a
spare piece of onion, it\'s time to add the aromatics. While you\'re
frying the aromatics, you\'ll likely need to lower the heat to medium so
that the oil doesn\'t get too much higher than 300°F (150°C).]{.mark}

[Add the sliced ginger first and fry for 15 seconds.]{.mark}

[Add the garlic and fry for about 5 seconds (basically, the amount of
time you may need to track down the next ingredient on your
counter).]{.mark}

[Add the shallots and fry for about 30 seconds.]{.mark}

[Add the red onion and fry for about 15 seconds.]{.mark}

[Add the star anise and continue to fry, stirring constantly for 2.5-3
minutes or until the ingredients are well-browned (not burnt!). Then
turn the heat down or off completely.]{.mark}

[With a mesh strainer or sieve, scoop out all the solid pieces. You can
push on them in the strainer a little to squeeze out the oil back into
the wok.]{.mark}

[Once you have removed all the solids, heat the oil back up to 300°F
(150°C). If you accidentally go too far and the oil gets too hot, bring
the temperature down by lowering the heat and adding a tbsp or so of
room temperature oil.]{.mark}

[When the aromatic oil has come back up to 300°F (149°C), turn off the
heat; it\'s time for the (somewhat) dramatic pour-over. Don\'t pour it
all at once! Dumping a huge volume of hot oil at once will scorch and
burn the chili mix.]{.mark}

[Bring the chili mix close to the oil to minimize risk of dripping and
bumping into obstacles.]{.mark}

[Pour just one ladle of hot oil slowly over the chili mix. It should
sizzle gently. Stir it in.]{.mark}

[Add a second ladle of hot oil, again pouring slowly, and stir it in,
and repeat with a third ladle of hot oil.]{.mark}

[Add **sesame seeds** (1 dash) and stir those in.]{.mark}

[Heat up the rest of the oil a little more. At this point, the batch of
chili oil and chili mix have been brought up to a temperature where
pouring in even hotter oil won\'t burn the solids anymore.]{.mark}

[Add the final ladle of the hot oil (this should just about finish all
the oil, though if you have more, feel free to use up the rest) and stir
it in. Add a quick drizzle of **sesame oil** (1 tsp) to intensify the
aromas of all the ingredients.]{.mark}

[Store this amazing chili oil in the fridge, and enjoy for several
months!]{.mark}

**Source:**
[[https://www.madewithlau.com/recipes/homemade-chili-oil]{.underline}](https://www.madewithlau.com/recipes/homemade-chili-oil)

**Batch 10/7/2023:**

*Chili Mix*

-   3 tbsp chili flakes (17g)

-   1 tbsp paprika

-   Oil

-   1tsp salt

-   1tsp sugar

-   1tsp white pepper

*Test*

-   1 tsp msg

-   ½ tsp sugar

*Oil*

-   1.5oz ginger

-   6oz\~ red onion

-   1.2oz\~ shallot

-   12 star anise

-   14 cloves garlic (50g\~)

-   3 ¼ cups oil (26 oz)

**Batch 11/12/2023:**

*Chili Mix (per jar)*

-   3 tbsp chili flakes (17g)

-   1 tsp paprika

-   1tsp salt

-   1tsp white pepper

-   1 tsp oil

*Oil (80 total oz)*

-   Small stalk ginger, peeled and sliced

-   Small red onion, sliced

-   Small shallot, sliced

-   12 star anise

-   10 cloves garlic, smashed

-   10 cups of oil, 80oz
