---
title: "Fermented Hot Sauce (w_ any peppers)"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Sauces and Condiments"]
---

**Ingredients:**

-   1 pound red serrano peppers or use any chili peppers, stems removed

-   1 quart unchlorinated water

-   3 tablespoons salt

-   ½-1 cup white wine vinegar to your preference use a good quality
    vinegar for better quality hot sauce

**Directions:**

1.  First, ferment the serrano peppers. Roughly chop the peppers, then
    pack them into a ball jar, leaving at least 1 inch of head space.
    The peppers may rise a bit when fermenting.

2.  Next, mix 1 quart unchlorinated water with 3 tablespoons sea salt.
    Pour just enough brine over the peppers to cover them, pressing them
    down a bit as you go. It is important to keep the peppers covered
    with brine to avoid spoilage. Check this daily.

3.  Screw on the lid and set the jar away from direct sunlight to
    ferment for at least 1 week. Ideal temperatures are between 55-75
    degrees F. The most active fermentation period is between 1-2 weeks,
    so be sure to monitor it during this time. "Burp" the jars often by
    unscrewing the lid a bit to let out some of the accumulating gases.
    Or, use an airlock or membrane for easier fermenting. See our page,
    "How to Ferment Peppers", for more detailed instruction.

4.  After 1-2 weeks, the fermenting activity will diminish and the brine
    will turn cloudy and taste acidic.

5.  Drain the peppers, but reserve the brine.

6.  Add the fermented peppers to a food processor or blender, along with
    1/2 cup of the brine and 1/2 cup vinegar. You can add more or less
    of each as desired to your preference. More brine will have more
    salty flavor, more vinegar will be more acidic.

7.  Process until smooth.

8.  Add the fermented hot sauce to a pot and bring to a quick boil.
    Reduce heat and simmer for 15 minutes. This will stop the
    fermentation process.

9.  Strain the mixture to remove the solids if desired, or use as-is for
    a thicker hot sauce. Pour into hot sauce bottles and enjoy.

10. You can add more vinegar or water to thin out the hot sauce.
