---
title: "Harissa"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Sauces and Condiments"]
---

**Ingredients:**

-   16 dried red chilies (New Mexico and guajillo chilies work well,
    remove seeds, membranes and stems. If you want a really hot paste,
    leave the membranes)

-   1/4 teaspoon caraway seeds

-   1 teaspoon cumin seeds

-   1 teaspoon coriander seeds

-   3 tablespoons extra-virgin olive oil

-   1/2 teaspoon kosher salt

-   3 cloves garlic

-   2 tablespoons freshly squeezed lemon juice

**Directions:**

1.  Put the dried chiles in a bowl and cover with boiling water. Let
    them sit for 20 minutes. Heat a small skillet over medium heat and
    dry roast the caraway, coriander, and cumin seeds, frequently
    stirring them, until very fragrant, about 4-5 minutes. Let them cool
    completely and then transfer them to a spice or coffee grinder (or
    mortar and pestle) and grind them to a fine powder.

2.  Next, drain and squeeze the chiles to release as much liquid as you
    can. Add them to a food processor along with the ground spices,
    olive oil, garlic, salt, and lemon juice. Process to a smooth paste.
    Add more olive oil if it's too dry. Transfer the paste to a glass
    jar and pour some extra olive oil on top, about 1/4 inch in depth.
    After each use, top it off with olive oil. Keep refrigerated. Will
    keep for about 3 weeks.

3.  Makes about 1 cup.
