---
title: "Hot Sauce (Dried Peppers)"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Sauces and Condiments"]
---

**Ingredients:**

-   2 cups lightly crushed and seeded dried chili peppers

-   2 cups water or enough to cover the peppers - FOR METHOD ONE

-   1 cup vinegar or as desired, FOR METHOD TWO

-   1 teaspoon garlic powder

-   1 teaspoon salt

-   \*Other ingredients as desired. See notes.

**Directions:**

[FOR METHOD ONE]{.underline}

1.  Lightly toast the dried chili peppers in a hot pan for a minute or 2
    per side, until they become slightly pliable and loosen the oils in
    the skins. This step is optional and develops more flavor.

2.  Remove from heat and add enough very hot water to cover the peppers.
    Let them steep for 15 to 20 minutes to soften.

3.  Strain the peppers but keep the steeping water.

4.  Add the rehydrated peppers to a food processor or blender along with
    1 cup of the steeping water (or use fresh water) vinegar (use
    anywhere from 2 tablespoons to 1 cup), garlic powder, salt, and
    other optional ingredients. Process until smooth.

5.  Taste and adjust with salt and vinegar. Strain if desired.

6.  Pour into bottles and enjoy, or simmer then in a pot for 10-20
    minutes to develop the flavors even more, then cool and bottle.
    Store in the refrigerator.

[FOR METHOD TWO]{.underline}

1.  Lightly toast the dried chili peppers in a hot pan for a minute or 2
    per side, until they become slightly pliable and loosen the oils in
    the skins. This step is optional and develops more flavor.

2.  Add water and vinegar, garlic powder, salt and other optional
    ingredients. Use less vinegar or water for thicker hot sauce. Simmer
    the peppers for 15 to 20 minutes to soften.

3.  Add the mixture to a food processor or blender along with vinegar
    (use anywhere from 2 tablespoons to 1 cup), garlic powder, salt, and
    other optional ingredients. Process until smooth.

4.  Taste and adjust with salt and vinegar. Strain if desired.

5.  Pour into bottles and enjoy, or simmer then in a pot for 10-20
    minutes to develop the flavors even more, then cool and bottle.
    Store in the refrigerator.

**Notes:**

[Water & Vinegar.]{.underline} I use 1 cup of each along with 2 cups
lightly crushed dried pepper pods. This results in a thin sauce, like
Tabasco or Crystal. If you\'d like a thicker sauce, use less water
and/or vinegar. Also, reduce the amount of vinegar for less tang. You
can also use other liquids. See my page on [[How to Make Hot
Sauce]{.underline}](https://www.chilipeppermadness.com/recipes/how-to-make-hot-sauce/)
for further discussion and ideas.

[Vinegar Options]{.underline}. Use your favorite vinegar. However,
you\'ll receive best results with a high quality vinegar.

[pH]{.underline}. If you\'d like your hot sauce to keep longer, shoot
for a pH of 3.5 or lower. If your pH is higher, adjust with more vinegar
or add citrus, then retest it.

[Other Ingredients]{.underline}. You can add in all sorts of other
flavor building ingredients, like onion, garlic, other peppers.
vegetables, herbs and spices, fruits, juices, alcohol, and so much more.

**Source:**
[[https://www.chilipeppermadness.com/recipes/how-to-make-hot-sauce-from-dried-peppers/]{.underline}](https://www.chilipeppermadness.com/recipes/how-to-make-hot-sauce-from-dried-peppers/)
