---
title: "Peach Scotch Bonnet Hot Sauce"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Sauces and Condiments"]
---

**Ingredients:**

-   6 ounces Scotch Bonnet peppers chopped

-   1 pound tomatoes chopped

-   1 peach peeled, pitted and chopped

-   2 cloves garlic chopped

-   ¼ cup apple cider vinegar

-   2 tablespoons honey

-   1 tablespoon mustard powder

-   1 teaspoon salt

-   ½ teaspoon ground cardamom (I used green cardamom)

-   ½ teaspoon black pepper

**Directions:**

1.  First, roughly chop the peppers, tomato, peach and garlic. Pack them
    into a large jar, leaving at least 1 inch of head space. The mixture
    may rise a bit when fermenting.

2.  Next, mix 1 quart unchlorinated water with 3 tablespoons sea salt.
    Pour just enough brine over the mixture to cover it, pressing them
    down a bit as you go. It is important to keep the mixture covered
    with brine to avoid spoilage. Check this daily.

3.  Screw on the lid and set the jar away from direct sunlight to
    ferment for at least 1 week. I fermented for 10 weeks. Ideal
    temperatures are between 55-75 degrees F. The most active
    fermentation period is between 1-2 weeks, so be sure to monitor it
    during this time. "Burp" the jars often by unscrewing the lid a bit
    to let out some of the accumulating gases. Or, use an airlock or
    membrane for easier fermenting.

4.  After 1-2 weeks, the fermenting activity will diminish and the brine
    will turn cloudy and taste acidic.

5.  When satisfied with your fermenting time, pour the contents,
    including brine, into a pot along with the remaining ingredients.
    Bring to a quick boil. Reduce heat and simmer for 15 minutes.

6.  Cool, then process with a food processor until nice and smooth.

7.  Pour into sterilized jars and seal. Refrigerate and enjoy. Tastes
    even better if you leave it mingle a week or longer.
