---
title: "Roasted Ghost Pepper Hot Sauce"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Sauces and Condiments"]
---

**Ingredients:**

-   2 ounces ghost peppers about 5-6 average sized ghost peppers

-   6 ounces carrot about 1 medium sized carrot

-   3 garlic cloves

-   2 tablespoons apple cider vinegar

-   ¼ teaspoon lemon extract or use the juice from 1 lemon

-   Salt to taste

-   ½ cup water for thinning, or use more as desired

**Directions:**

1.  Preheat your oven to 350 degrees F.

2.  Slice the ghost peppers in half lengthwise (be sure to wear gloves!)
    and place them on a lightly oiled baking sheet.

3.  Peel and slice the carrots in half and set them on the baking sheet.

4.  Slice the ends off of the garlic cloves and set them on the baking
    sheet. This will let them squeeze out of their skins easily.

5.  Bake the veggies for 20 minutes, or until the carrots have
    sufficiently softened.

6.  Remove and give the carrots and ghost peppers a rough chop. Set them
    into a food processor.

7.  Squeeze the garlic out of their skins into the food processor.

8.  Add the apple cider vinegar, lemon extract, salt to taste and about
    a quarter cup of water. Process until smooth.

9.  Adjust the consistency of the sauce with a bit more water to your
    personal preference. Enjoy!
