---
title: "Spicy Serrano Hot Sauce"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Sauces and Condiments"]
---

**Ingredients:**

-   1 pound serrano peppers

-   3 tablespoons sea salt

-   1 quart unchlorinated water

-   3 cloves garlic minced

-   3 ounces white wine vinegar

-   1.5 ounces reposado tequila

-   Juice from 1 lime

**Directions:**

1.  First, ferment the serrano peppers. Process your fresh peppers in a
    food processor. If you don't have a processor, use a mortar and
    pestle or simply rough chop them. Pack them into a jar, leaving at
    least 1 inch of head space. The peppers may rise a bit when
    fermenting.

2.  Next, mix 1 quart unchlorinated water with 3 tablespoons sea salt.
    Pour just enough brine over the peppers to cover them, pressing them
    down a bit as you go. Discard or save any remaining brine for
    another use. It is important to keep the peppers covered with brine
    to avoid spoilage. Check this daily.

3.  Screw on the lid and set the jar away from direct sunlight to
    ferment for at least 1 week. Ideal temperatures are between 55-75
    degrees F. The most active fermentation period is between 1-2 weeks,
    sobe sure to monitor it during this time. "Burp" the jars often by
    unscrewing the lid a bit to let out some of the accumulating gases.
    Or, use an airlock or membrane for easier fermenting. See our page,
    "How to Make Fermented Pepper Mash", for further instruction.

4.  After 1-2 weeks, the fermenting activity will diminish and the brine
    will turn cloudy and taste acidic.

5.  Pour the fermented serrano peppers, including the brine, into a pot
    along with garlic, vinegar and tequila. Bring to a quick boil.
    Reduce heat and simmer for 15 minutes. NOTE: If you feel the brine
    will make your hot sauce too salty, you can strain the peppers and
    use fresh water instead, just enough to cover the peppers in the
    pot. Or, use a combination of brine and fresh water.

6.  Cool slightly then add to a food processor with the lime juice.
    Process until smooth.

7.  Strain the mixture to remove the solids, if desired. Pour into hot
    sauce bottles and enjoy.
