---
title: "Ultimate Pesto"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Sauces and Condiments"]
---

**Ingredients:**

-   Two cups greens

    -   Parsley

    -   Green Onions

    -   Chives

    -   Leafy greens and/or herbs

        -   You can mix and match depending on what you have on hand

        -   I.e. Cilantro, Swiss Chard,

-   Half cup oil

-   Half cup cheese (Dry crumbling or grating)

    -   Cheddar

    -   Feta

    -   Parmesan

    -   Flexible recipe for cheese on hand

        -   Miso if you're feeling heretical

-   Two-three cloves of garlic

-   Quarter cup nuts.

    -   Pine Nuts

    -   Almonds

    -   Cashews

    -   Walnuts

    -   Sunflower Seeds

        -   Flexible Recipe for nuts on hand

        -   Seeds also work

**Directions:**

1.  First put your garlic, nuts, and any personal flavor upgrades (i.e.
    serrano, red chili, etc.) in the food processor for 15 seconds, a
    quick chop. Broken down enough so they aren't rattling all over.

2.  Next, scrape the sides of the food processor and add in the cheese.
    Depending on the type, the paste may be more clumpy.

3.  Then, roughly chop your greens before adding those into the food
    processor. Run the processor until you reach your desired texture.
    Once there, season with salt and pepper to taste.

4.  Finally, add in a bit of the oil before running the processor again.
    As you begin to drizzle some, start the processor and continuously
    stream more oil in. Note that using fattier nuts will require less
    oil for a similar ratio. Additionally, add in a splash of cold water
    if you would like.

5.  Store in a resealable jar with a bit of olive oil on top of the
    mixture. Then, put some plastic wrap over the top of the jar mouth,
    pressing down a bit, before sealing.

**Notes:**

-   The oil acts as a water and airproofing for the mixture, the plastic
    wrap serves as another layer as well.

-   Ratio is **2 : ½ : ½ : 2 : ¼ (Cups of Greens to Oil to Cheese to
    Garlic Cloves to Nuts)**
