---
title: "Mapo Tofu"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Tofu"]
---

**Ingredients:**

*Marinade*

-   4 oz (120 g) ground pork (or chicken, or turkey) (\*Footnote 1)

-   2 teaspoons Shaoxing wine (or dry sherry)

-   1 teaspoon light soy sauce

-   1/2 teaspoon minced ginger

*Braising*

-   1 teaspoon cornstarch (optional) (\*Footnote 2)

-   2 teaspoons Sichuan peppercorns , increase to 3 teaspoons if you
    like your dish extra numbing, or reduce to 1 teaspoon if your
    Sichuan peppercorns are extra fresh

-   1 tablespoon peanut oil (or vegetable oil)

-   3 tablespoons Doubanjiang , reduce to 2 tablespoons for a less
    saltier and less spicy taste

-   2 green onion , chopped

-   1 block (400-g / 14-oz) firm or medium firm tofu , cut into 1.5cm
    (1/2 inch) squares

-   1 cup chicken stock (or water)

-   2 teaspoons homemade chili oil (\*Footnote 3)

-   1/4 teaspoon five-spice powder

-   1 teaspoon sugar (or to taste)

**Directions:**

1.  Combine ground meat, cooking wine, soy sauce, and ginger in a small
    bowl. Mix well.

2.  Combine cornstarch with 1 tablespoon of water in a small bowl. Mix
    well and set aside.

3.  Heat the oil and Sichuan peppercorns in a large nonstick skillet
    over medium-high heat. When the Sichuan peppercorns turn dark brown
    and crispy, scoop them out with a spatula and transfer into a bowl
    layered with paper towels to soak extra oil. Save to use for
    garnishing the dish (Optional).

4.  Add the ground meat and Doubanjiang. Cook over medium heat and chop
    the ground meat into small bits with a spatula, until pork is evenly
    coated with Doubanjiang and fully cooked through. Add green onion
    and stir fry for another minute.

5.  Spread tofu evenly on top of ground pork (\*Footnote 4). Add chili
    oil, five-spice powder, and sugar. Pour in the broth and cook until
    brought to a simmer. Simmer, covered, over medium-low heat for 8 to
    10 minutes, or until the sauce has reduced to half the original
    amount. Taste the tofu with some broth (be careful, it will be very
    hot!). Adjust seasoning by adding salt if needed. If the dish is too
    spicy, add another teaspoon of sugar to balance it out. Gently mix
    well with spatula.

6.  (Optional) Meanwhile, grind the fried Sichuan peppercorns (you used
    when heating up the oil) in a coffee grinder or using mortar and
    pestle.

7.  Mix cornstarch water again until fully dissolved and swirl it into
    the skillet. Gently stir a few times with a spatula, until sauce
    thickens. Turn off heat and transfer everything to a bowl.

8.  Garnish with extra green onion and a small pinch of the ground
    Sichuan peppercorns, if using (\*Footnote 5), if using. Serve hot
    over steamed rice or by itself as main.
