---
title: "Authentic Hot and Sour Soup"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Soups"]
---

**Ingredients:**

[Rehydrate (Optional):]{.underline}

-   1/3 cup dried shiitake mushrooms

-   1/4 cup dried woodear mushrooms

-   1/4 cup dried lily flowers

[Marinade (Optional):]{.underline}

-   1/2 lbs (230 g) pork loin (or chicken breast) cut into thin strips

-   1/2 tablespoon Shaoxing wine or dry sherry

-   1/4 teaspoon salt

-   1/2 tablespoon cornstarch

[Soup:]{.underline}

-   2 teaspoons minced ginger

-   2 green onions chopped

-   2 tablespoons Chinkiang vinegar

-   1 teaspoon white pepper powder (or 1/2 teaspoon white pepper powder
    for a less spicy dish)

-   6 cups water or chicken stock (\*Footnote 3)

-   1/2 block (8 oz / 227 g) firm tofu, cubed

-   1 tablespoon light soy sauce or soy sauce

-   3 tablespoons cornstarch

-   1 teaspoon salt or to taste

-   2 eggs beaten

-   1 teaspoon sesame oil

**Directions:**

1.  Gently rinse dried shiitake mushrooms, dried wood ear mushrooms, and
    lily flowers with tap water. Soak each of them with 1.5 to 2 cups
    warm water in three big bowls. Rehydrate for 30 minutes to 1 hour,
    until tender. Slice mushrooms into strips. Snip off the tough ends
    of lily flowers and discard. Remove tough ends of wood ear
    mushrooms, then chop into bite-sized pieces. Reserve the marinating
    water from lily flower and shiitake mushrooms, 2 cups in total

2.  Combine pork, Shaoxing wine, salt and cornstarch in a bowl. Mix well
    by hand. Marinate for 10 - 15 minutes.

3.  Add Chinkiang vinegar and white pepper into a small bowl. Mix well
    until the white pepper is completely dissolved.

4.  Add water or chicken stock, ginger, and green onion into a pot and
    heat over medium-high heat. If you reserved the marinating liquid
    from step one, you can add it plus 4 cups water or chicken stock.

5.  Add rehydrated wood ear mushrooms, shiitake mushrooms, lily flowers,
    and tofu to the pot. Cook until bringing to a simmer. Add soy sauce
    and turn to medium-low heat.

6.  Mix the cornstarch with 1/4 cup of water in a bowl until cornstarch
    is fully dissolved. Slowly swirl the cornstarch slurry into the
    soup. Stir to thicken the soup.

7.  Add the pork from step one into the soup, stirring several times to
    prevent the pork strips from sticking together. Add the salt. Slowly
    swirl in the beaten egg and stir well. The egg should be scattered
    and not clotted.

8.  Remove the pot from stove. Add the vinegar and pepper mixture and
    stir to mix well.

9.  Garnish with cilantro and drizzle with sesame oil. Give it a final
    stir. Taste the soup and add more salt if needed.

**Notes:**

-   If you do not have these dry ingredients, you can use half a pound
    of fresh mushrooms instead. Then use chicken stock instead of water
    to make the soup.

-   **[From the first time]{.underline}** try using double the vinegar,
    as well as chili oil at the end with sesame oil to give the hot/sour
    flavors more punch

    -   **AND** use half the amount of cornstarch in the slurry, ended
        up being very thick and more stew like
