---
title: "Blue Zone_s Minestrone"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Soups"]
---

**Ingredients:**

-   1/3 lbs dry garbanzo beans

<!-- -->

-   1/3 lbs dry white beans

-   1/3 lbs dry pinto or red beans

-   1.5 cups 1-2" cubed potatoes

-   6-8 cups of water or veg stock if you like it richer

-   1 medium onion, chopped

-   5 stalks celery chopped

-   5 carrots, chopped

-   8 cloves garlic, chopped,

-   1 bay leaf

-   1 tsp oregano

-   2 tbs olive oil

-   1 tsp red or black pepper (red makes it hotter)

-   1 -- 14 oz can of chopped tomatoes or 5 Roma tomatoes

-   Salt to taste

**Directions:**

1.  I like to soak beans overnight or if you forget, Microwave dry beans
    in a bowl of water as you chop the other ingredients.

2.  Sauté all vegetables in olive oil over low heat until onions are
    clear.

3.  Add beans and a can of tomatoes, potatoes, oregano, bay leaf and
    slow cook until beans are tender.

4.  I let it cook on extremely low heat all day, adjusting water so it's
    thicker than a soup and thinner than a stew. (For quicker soup

5.  pressure cook or use an instapot for 5 minutes and let cooker cool
    naturally)

6.  Finish with avocado when serving.

7.  Freeze leftovers in single-serving glass Tupperware.

**Notes:**

-   More healthy recipes here: https://danbuettner.com/recipes/
