---
title: "Chicken Picatta"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Chicken"]
---

**Ingredients:**

-   2 large lemons

-   6 boneless, skinless, chicken breasts, trimmed and pounded until 1/4
    inch thick

-   1 pinch salt

-   1 pinch black pepper

-   1/2 cup flour

-   4 tablespoons olive oil

-   1 small shallot, minced (about 2 tablespoons)

-   1 cup low-sodium chicken broth

-   2 tablespoons capers, drained

-   3 tablespoons unsalted butter, softened

-   2 tablespoons fresh parsley, minced

-   6 servings couscous or angel hair pasta

**Directions:**

1.  Cut one lemon in half lengthwise. Trim the ends from one half and
    cut across into thin slices about 1/8 inch thick; set aside. Juice
    the remaining half and whole lemon to obtain about 1/4 cup juice;
    set aside.

2.  Season both sides of the chicken breasts generously with salt and
    pepper. Place flour into a shallow dish or pan. Coat each breast
    with flour, and shake to remove excess.

3.  Heat 2 tablespoons of olive oil in a large, heavy-bottomed skillet
    over medium-high heat until hot, about 2 minutes. Cook half the
    batch in the skillet without moving them until lightly browned on
    the first side, 2 to 2 1/2 minutes. Turn and cook until the second
    side is lightly browned, 2 to 2 1/2 minutes longer. Transfer to a
    plate kept warm in the oven, or cover with aluminum foil. Add the
    remaining 2 tablespoons of oil to the skillet and heat until
    shimmering. Add remaining chicken pieces and repeat. Add cooked
    chicken to previous batch and keep warm in 200 degree oven.

4.  Using the pan in which you cooked the chicken, sauté the shallots in
    the oil and browned bits remaining in the pan. Once shallots become
    translucent, add the chicken broth and lemon slices. Allow to cook
    until lemon slices are well-softened.

5.  Add the capers and lemon juice, and allow to reduce to concentrate
    flavors. Remove pan from heat and swirl in the butter until it melts
    and thickens the sauce. Swirl in the parsley. Spoon over chicken and
    serve immediately over a bed of couscous or angel hair pasta.

**Source:**
[[https://food52.com/recipes/26564-classic-chicken-piccata]{.underline}](https://food52.com/recipes/26564-classic-chicken-piccata)
