---
title: "Chongqing Chicken (La Zi Ji)"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Chicken"]
---

**Ingredients:**

*Marinade:*

-   1 lb (450 g) boneless skinless chicken thigh , cut into 1" (2.5 cm)
    cubes (or breast)

-   1 tablespoon Shaoxing wine (or dry sherry)

-   1 tablespoon light soy sauce (or soy sauce)

*Spice mix:*

-   1 tablespoon toasted sesame seeds , and more to garnish

-   1 to 3 cups whole dried red Sichuan chilies (\*Footnote 1)

-   2 tablespoons Sichuan chili flakes

-   1 teaspoon sugar

*Chicken coating:*

-   1/4 cup cornstarch

-   1 teaspoon cayenne powder (\*Footnote 2)

-   1 teaspoon ground Sichuan peppercorns (\*Footnote 3)

-   3/4 teaspoon salt

*Cook*

-   1/4 to 1/3 cup peanut oil (or vegetable oil)

-   2 teaspoons Sichuan peppercorns

-   5 garlic cloves , thinly sliced

-   1 thumb ginger , minced

-   4 green onions , sliced

-   1 cup chopped cilantro , and more for garnish

**Directions:**

1.  To marinate the chicken: Combine chicken pieces, Shaoxing wine, and
    soy sauce in a medium-sized bowl. Mix well and marinate for 10 to 15
    minutes.

2.  For the spice mix: Combine all the spice mix ingredients in a big
    bowl.

3.  For the chicken coating: Mix cornstarch, cayenne powder, ground
    Sichuan peppercorns and salt in a large ziplock bag. Shake to mix
    well

4.  When you're ready to cook, drain the chicken pieces and discard the
    marinating liquid. Transfer the chicken pieces into the bag with the
    cornstarch mixture. Shake the bag to coat the chicken, then use your
    hands to massage the bag so the spice is evenly mixed in. There
    should be little / no dried ingredients left in the bag. Massage the
    bag more if you still see a lot of uncoated cornstarch. On the other
    hand, if the chicken pieces look wet, sprinkle on a bit more
    cornstarch.

5.  To cook the stir fry: Heat a large skillet (or a wok) over
    medium-high heat until wisps of smoke start to rise. Add oil. (Or
    add oil in the pan and heat together if using a nonstick skillet.)
    When oil is hot, spread out the chicken pieces without overlapping
    them. Use a pair of tongs or chopsticks to separate the chicken
    pieces as much as possible, then leave the chicken undisturbed until
    the bottom turns golden brown. Flip to cook the other side until
    golden and the inside of the chicken is no longer pink. Stir a few
    times to make sure the surface of the chicken is evenly cooked. Turn
    to medium-low heat. Transfer the cooked chicken to a large plate.

6.  You should still have some oil in the pan. If not, add 2 tablespoons
    of oil. Add the Sichuan peppercorns. Cook and stir until the color
    turns dark brown. Remove them from the pan. (\*Footnote 3)

7.  Add the garlic, ginger and green onions. Stir a few times to release
    the fragrance.

8.  Add the bowl of spice mix with the peppers. Quickly stir until the
    peppers just turn a bit darker without turning black.

9.  Return the cooked chicken into the pan. Cook and stir until well
    mixed. Add the cilantro and mix a few times. Turn off heat. Transfer
    everything to a plate with chili peppers prominently displayed. Top
    with more cilantro for garnish, if needed.

**Notes:**

-   Choose fat and large chili peppers that have a milder taste. If you
    cannot find Sichuan chili peppers, you can alternatively use Korean
    chili peppers. Do not use Thai Bird's eye chili peppers. I know 3
    cups sounds like a LOT of peppers if you cook the dish the authentic
    way. Alternatively you can use 1 cup of chili peppers, which affects
    the dish's appearance but not the taste.

-   This recipe creates a rich numbing spicy taste, just like the
    authentic La Zi Ji I had in China. If you're not sure about the
    spiciness level or want a milder dish, use 1/2 teaspoon cayenne
    powder and 1/2 teaspoon Sichuan peppercorns instead.

-   In China, whole Sichuan peppercorns are always left in the dish.
    However you will need to pick them out of the dish when eating
    because it's not very pleasant if you accidentally bite into one. So
    you can infuse the peppercorns in the oil and then remove them like
    stated in the recipe. On the other hand, leave them in if you prefer
    a more authentic experience. In that case, toast the Sichuan
    peppercorns lightly or add them with the dried chili pepper mixture
    together in step 8.
