---
title: "NYT Chicken Shawarma"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Chicken"]
---

**Ingredients:**

-   2 lemons, juiced

-   ½ cup plus 1 tablespoon olive oil

-   6 cloves garlic peeled, smashed, and minced

-   1 teaspoon kosher salt

-   2 teaspoons freshly ground black pepper

-   2 teaspoons ground cumin

-   2 teaspoons paprika

-   ½ teaspoon turmeric

-   A pinch of cinnamon

-   Red pepper flakes to taste

-   2 pounds boneless skinless chicken thighs

-   1 large red onion, peeled and quartered

-   2 tablespoon chopped fresh parsley

**Directions:**

1.  Prepare a marinade for the chicken. Combine the lemon juice, ½ cup
    olive oil, garlic, salt, pepper, cumin, paprika, turmeric, cinnamon,
    and red pepper flakes in a large bowl, then whisk to combine. Add
    the chicken and toss well to coat. Cover and store in the
    refrigerator for at least 1 hour and up to 12 hours.

2.  When ready to cook, heat the oven to 425 degrees. Use the remaining
    tablespoon of olive oil to grease a rimmed sheet pan. Add the
    quartered onion to the chicken and marinade, and toss once to
    combine. Remove the chicken and onion from the marinade, and place
    on the pan, spreading everything evenly across it.

3.  Put the chicken in the oven and roast until it is browned, crisp at
    the edges and cooked through, about 30 to 40 minutes. Remove from
    the oven, allow to rest 2 minutes, then slice into bits. (To make
    the chicken even more crips, set a large pan over high heat, add a
    tablespoon of olive oil to the pan, then the sliced chicken, and
    saute until everything curls tight in the heat.) Scatter the parsley
    over the top and serve with tomatoes, cucumbers, pita, white sauce,
    hot sauce, olives, fried eggplant, feta, rice -- really anything you
    desire.
