---
title: "Sesame Chicken"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Chicken"]
---

**Ingredients:**

-   1 lbs (450 g) chicken thighs , cut to bite-size chunks

-   1 tablespoon vegetable oil

-   1/2 teaspoon salt

-   1 egg , beaten

-   1/2 cup cornstarch

Sauce

-   1/2 cup chicken stock

-   2 tablespoons Shaoxing wine (or dry sherry for gluten-free)

-   2 tablespoons soy sauce (or tamari for gluten-free)

-   2 tablespoons Chinkiang vinegar (or rice vinegar for gluten-free)

-   4 tablespoons sugar

-   2 teaspoons sesame oil

-   2 teaspoons cornstarch

-   1 tablespoon sesame seeds , toasted

Cook

-   1/4 to 1/3 cup vegetable oil

-   2 cloves garlic , minced

-   2 green onions , sliced

**Directions:**

1.  Combine chicken pieces, vegetable oil, and salt in a big bowl. Mix
    well and let marinate for 10 to 15 minutes.

2.  Combine all the sauce ingredients in a small bowl and set aside.

3.  Add the beaten egg into the bowl with the chicken. Stir to mix well.
    Add cornstarch. Stir to coat chicken, until it forms an uneven
    coating with a little dry cornstarch left unattached.

4.  Heat oil in a large nonstick skillet over medium high heat until
    hot. Add chicken all at once and spread out into a single layer in
    the skillet. Separate chicken pieces with a pair of tongs or
    chopsticks.

5.  Cook without touching the chicken for 2 to 3 minutes, or until the
    bottom turns golden. Flip to brown the other side, 2 to 3 minutes.
    Transfer chicken to a big plate and remove the pan from the stove.
    Let cool for 2 to 3 minutes.

6.  Wipe the extra oil from the pan using a few layers of paper towel
    held in a pair of tongs, leaving about 1 tablespoon of oil in the
    pan. Add the garlic and green onion. Stir fry a few seconds to
    release the aroma.

7.  Stir the sauce again to thoroughly dissolve the cornstarch. Add to
    the pan and cook until thickened.

8.  Add the chicken back into the pan and stir to mix well.

9.  Transfer to a plate and serve hot over steamed rice.
