---
title: "Weissman Fried Chicken (Two Ways)"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Chicken"]
---

**Ingredients:**

**[Marinade]{.underline}:**

-   2 cups (473ml) buttermilk

-   1.5 teaspoons (8g) MSG

-   1 tablespoon (12g) salt

-   1 tablespoon (9g) white pepper

-   1 tablespoon (12g) garlic powder

-   1 tablespoon (9g) smoked paprika

-   2 lbs (907g) chicken thighs or drumsticks

**[Flour Dredge]{.underline}**:

-   2.5 cups (375g) all-purpose flour

-   2 teaspoon (2g) dried thyme

-   1 tablespoon (12g) garlic powder

-   1 teaspoon (3g) onion powder

-   2 teaspoons (5g) celery powder

-   2 tablespoons (18g) smoked paprika

-   2 teaspoons (10g) MSG

-   2 tablespoons (23g) kosher salt

**[Sauce]{.underline}**:

-   1/2 cup (160g) gochujang

-   6 tablespoons (104g) ketchup

-   1/4 cup (50g) regular soy sauce

-   5 tablespoons (160g) brown rice vinegar

-   1/4 cup (60g) mirin

-   6 tablespoons (46g) grated palm sugar

-   8 cloves grated garlic

-   Sesame seeds for garnish

-   Thinly sliced green onions for garnish

**[Korean Fried Chicken]{.underline}** (Yangnyeom Chicken):

-   2 lbs (907g) chicken thighs or drumsticks

-   1 tablespoon (17g) grated ginger

-   1 teaspoon (under 1g) finely ground black pepper

-   Salt to taste

-   1 cup (165g) corn starch

-   1/4 teaspoon (under 1g) baking soda

**Directions:**

**[Marinade/Flour Dredge]{.underline}**:

-   In a medium bowl, add all ingredients for the marinade minus the
    chicken. Whisk together until homogenous. In a separate large bowl,
    add all ingredients for flour dredge and whisk until combined.

-   Add your chicken to your marinade, making sure that it's fully
    submerged; let it sit for at least 5 minutes at room temperature or
    overnight in the fridge, covered with plastic wrap.

-   Fill a heavy bottom pot with vegetable oil and heat to 350F.

-   Remove chicken from marinade and toss in your seasoned dredge; press
    the dredge aggressively to the chicken to coat it thoroughly. Once
    completely coated, place on a baking sheet and repeat with the rest.

-   In two or three batches, fry your chicken for 5 to 7 minutes each or
    until golden brown and an internal temperature of 165 Fahrenheit.

-   Remove, drain on a wire rack and repeat with the rest of your
    chicken. Eat while hot and fresh.

**[Sauce]{.underline}**:

-   In a medium saucepan, add gochujang paste, ketchup, soy sauce, rice
    vinegar, mirin, palm sugar, and whisk until homogenous. Heat that
    over medium heat until a light simmer and let it reduce for one
    minute, stirring often.

-   Immediately remove from the heat and stir in garlic.

**[Korean Fried Chicken]{.underline}** (Yangnyeom Chicken):

-   In a medium-sized bowl, add chicken ginger, black pepper, generous
    salt to taste, and toss it together: let it sit for at least 5 min
    at room temperature or cover with plastic wrap and place in the
    fridge overnight.

-   In a large bowl, combine cornstarch, baking soda, and salt to taste.

-   Fill a heavy bottom pot with vegetable oil and heat to 325F.

-   Remove chicken from marinade and toss it into your dredge; press the
    dredge aggressively to the chicken until fully coated. Then shake
    off the excess; fry the chicken in batches for 5 minutes till just
    cooked through and a pale golden. Remove and drain on a wire rack.

-   Increase oil temperature to 375F, and place your chicken back into
    the fryer for 1 or 2 more minutes or until golden brown and crispy
    and an internal temperature of 165F.

-   Place your fried chicken in a bowl and toss it with as much sauce as
    your desire, making sure all the chicken gets completely coated with
    the sauce.

-   Optionally garnish with white toasted sesame seeds and green onion.
