---
title: "Simple Veal Bolognese"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Veal"]
---

**Ingredients:**

-   1 1/2 tbsp olive oil

-   2 garlic cloves , minced

-   1 onion , finely chopped (brown, yellow or white)

-   1 lb / 500g ground veal (or ground beef)

-   1/2 cup (125 ml) dry red wine (sub water or beef broth/stock)

-   2 beef bouillon cubes , crumbled OR granulated beef bouillon

-   800g / 28 oz can crushed tomato (or tomato passata)

-   2 tbsp tomato paste

-   2 tsp Worcestershire sauce

-   2 dried bay leaves

-   2 sprigs fresh thyme (or 1/2 tsp dried thyme or oregano)

-   3/4 tsp cooking salt (kosher salt)

-   1/2 tsp black pepper

-   400 g / 13 oz spaghetti , dried

-   Parmesan cheese and finely chopped parsley (optional)

**Directions:**

1.  **Sauté --** Heat oil in a large pot or deep skillet over medium
    high heat. Add onion and garlic, cook for 3 minutes or until light
    golden and softened.

2.  **Cook beef --** Turn heat up to high and add veal. Cook, breaking
    it up as your go, until browned.

3.  **Reduce wine --** Add red wine. Bring to simmer and cook for 1
    minute, scraping the bottom of the pot, until the alcohol smell is
    gone.

4.  **Simmer --** Add the remaining ingredients. Stir, bring to a simmer
    then turn down to medium so it bubbles gently. Cook for 20 -- 30
    minutes (no lid), adding water if the sauce gets too thick for your
    taste. Stir occasionally.

5.  **Slow simmer option:** really takes this to another level, if you
    have the time! Add 3/4 cup of water, cover with lid and simmer on
    very low for 2 -- 2.5 hours, stirring every 30 minutes or so.
    (Note 5) Uncover, simmer 20 minutes to thicken sauce. (Note 6 for
    slow cooker)

6.  **Taste** and add more salt it desired. Serve over spaghetti --
    though if you have the time, I recommend tossing the sauce and pasta
    per steps below.

#### **Tossing Sauce and Spaghetti (optional)**

1.  Bring a large pot of salted water to boil. Add pasta and cook per
    packet directions MINUS 1 minute.

2.  Scoop out a mug of pasta cooking water and set aside, then drain the
    pasta.

3.  Add pasta into the bolognese sauce with about 1/2 cup (125 ml) of
    reserved pasta water over medium heat. Toss gently for 1 1/2 -- 2
    minutes, or until the spaghetti turns red and the sauce thickens.

4.  Divide between bowls. Garnish with parmesan and parsley if desired.
