---
title: "Italian Chopped Brussels Sprouts Salad"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Salads"]
---

**Ingredients:**

[For the Italian dressing:]{.underline}

-   1/3 cup olive oil

-   3 tablespoons red wine vinegar

-   1-2 teaspoons sugar or honey, depending on how sweet you like your
    dressing

-   1 clove garlic, finely minced

-   1 teaspoon dijon mustard

-   1 teaspoon italian seasoning

-   ½ teaspoon salt

-   Freshly ground black pepper

[For the salad:]{.underline}

-   1 pound brussels sprouts, ended trimmed and outer leaves removed

-   1 (15 ounce) can chickpeas, rinsed and drained

-   4-6 oz thinly sliced Genoa salami, cut in half or julienned

-   1 1/2 cups cherry or grape tomatoes, halved

-   ½ cup pitted sliced kalamata or sliced black olives

-   ¼ cup sliced pepperoncinis

-   ½ small red onion, thinly sliced

-   ½ cup cubed provolone cheese

-   ¼ cup shaved or shredded parmesan

**Directions:**

1.  Make the dressing: in a medium bowl, whisk together the olive oil,
    red wine vinegar, sugar/honey, garlic, dijon, italian seasoning,
    salt and pepper.

2.  Next, shred the brussels sprouts by using a food processor with the
    slicing attachment and pulse until the brussels sprouts are thinly
    sliced. If you don't have a food processor, feel free to use a sharp
    knife to thinly slice.

3.  Add shredded brussels to a large bowl and pour the dressing all
    over. Next use a tongs to coat the brussels with the dressing. Let
    the dressing sit and marinate the brussels for 30 minutes. While the
    brussels marinate and soak up the dressing, you can chop and prep
    all your other ingredients.

4.  Next add in the chickpeas, salami, tomatoes, olives, pepperoncinis,
    red onion, provolone cheese cubes, shaved parmesan. Toss to combine.
    Serve immediately with extra black pepper. Serves 4 to 6.

**Source:**
[[https://www.ambitiouskitchen.com/italian-chopped-brussels-sprouts-salad/?fbclid=IwAR3i2F4gLqo3c4NXtL6bgw3ZiZsH5oTnNAsESltmvYy-D1-3RDnMk0RbQlE]{.underline}](https://www.ambitiouskitchen.com/italian-chopped-brussels-sprouts-salad/?fbclid=IwAR3i2F4gLqo3c4NXtL6bgw3ZiZsH5oTnNAsESltmvYy-D1-3RDnMk0RbQlE)

**Notes:**

-   Chickpeas with it was, meh, trying quinoa, couscous or another bean
    may be better

-   Pickled brussels didn't work as well

-   Kale was good with it

-   Don't need too much meat
