---
title: "Quinoa Mediterranean Salad"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Salads"]
---

**Ingredients:**

[Salad:]{.underline}

-   1 cup uncooked quinoa

-   2 cups water or stock

-   15 oz. can garbanzo beans drained and rinsed

-   10 oz. cherry tomatoes sliced

-   1 medium red onion finely sliced

-   1 cup chopped English cucumber halved

-   3/4 cup pitted kalamata olives halved

-   1/2 cup chopped fresh mint

-   4 oz. feta cheese crumbles

-   *Optional*: Shredded chicken

[Dressing:]{.underline}

-   6 tablespoons hummus

-   2 teaspoons minced garlic

-   2 tablespoon balsamic

-   2 tablespoon lemon juice

-   1 tablespoon kalamata olive juice

**Directions:**

1.  *Optional*: If making shredded chicken, get two medium or large
    sized breasts (1.5lbs\~ total). Place them in a medium sized pot,
    sear both sides of the chicken on medium high, then cover with about
    2-2.5 cups of chicken stock (or water with the appropriate amount of
    bouillon). Bring the stock to a boil, then cover and put heat on low
    for about 15-20 minutes or until the chicken shreds easily with a
    fork. Shred it up (conversely you can use a hand beater with soft
    paddles) and then use the leftover stock to cook the quinoa.

2.  Prepare quinoa by placing quinoa and water into a medium-sized pot
    (or just use a rice cooker). Bring quinoa to a boil over medium-high
    heat and then turn the burner down to low, cover, and let simmer for
    15 minutes or until water has absorbed. Remove from heat and let
    cool for 15 minutes before placing in the refrigerator to chill.

3.  Next, prepare the dressing by placing all ingredients into a jar.
    Place the lid on the jar and shake to combine. Add water to thin the
    dressing out, if needed.

4.  For the salad, place the chilled quinoa into a large bowl and then
    add the rest of the salad ingredients. Drizzle on all of the
    dressing and toss to combine.

5.  Serve chilled.

**Notes:**

-   It's possible to meal prep this, just pre-cut all extra ingredients
    and put them in containers. Afterwards, assemble everything
