---
title: "Infused Alcohol"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Drinks"]
---

**Ingredients:**

-   16 ounces alcohol Use vodka, tequila, bourbon or whisky, gin,
    moonshine, or your own favorite type.

-   3 chili peppers Medium Sized. Use jalapeno peppers for milder heat,
    serrano pepeprs for mid-level heat, habanero peppers for hot, or
    ghost peppers or hotter for a truly hot and spicy alcohol.

**Directions:**

1.  Slice the chili peppers in half and add them to the bottle of
    alcohol. Be sure they float down beneath the alcohol and are not
    exposed to the air. Screw on the cap.

2.  Alternatively, you can add the peppers to a jar and pour the alcohol
    over them.

3.  Let the peppers steep in the alcohol for 2 days. You can steep them
    for anywhere from 2 hours to several weeks or longer.

4.  Test the alcohol at intervals until you achieve the level of flavor
    and infusion you would like.

5.  Strain out the peppers and enjoy.

**Sources:**
[[https://www.chilipeppermadness.com/cooking-with-chili-peppers/how-to-infuse-alcohol-with-chili-peppers/#wprm-recipe-container-16905]{.underline}](https://www.chilipeppermadness.com/cooking-with-chili-peppers/how-to-infuse-alcohol-with-chili-peppers/#wprm-recipe-container-16905)
