---
title: "Miso Glazed Cod"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Cod"]
---

**Ingredients:**

-   4 fillets sablefish (gindara) (4-6 oz or 113-170 g per fillet;
    skin-on; about 1 inch or 2.5 cm thick)

-   2 tsp Diamond Crystal kosher salt

-   2 Tbsp sake (to clean the fish and remove its odor)

For the Miso Marinade with Saikyo Miso (Traditional)

-   6 Tbsp Saikyo miso (Kyoto-style white miso) (西京味噌, a sweet white
    miso)

-   3 Tbsp mirin

-   3 Tbsp sake (do not substitute)

For the Miso Marinade with Regular White Miso (Optional)

-   6 Tbsp white miso (for miso types that are saltier than white miso,
    add more mirin or/and sugar)

-   3 Tbsp mirin

-   3 Tbsp sake (do not substitute)

-   1 Tbsp sugar

**Directions:**

[Before You Start:]{.underline}

1.  Select the freshest fish possible, as you will be marinating this
    fish for a few days. Please note that this recipe requires a
    marination time of 2--3 days. If you use skinless fish, marinate it
    for a shorter period of time. You can also use salmon and sea bass
    in this recipe.

[To Marinate the Fish (2--3 days before serving)]{.underline}

2.  Sprinkle 2 tsp Diamond Crystal kosher salt over 4 fillets sablefish
    (gindara) and set it aside for 30 minutes. The salt will draw out
    excess moisture and reduce the fish's odor.

3.  Meanwhile, make the marinade. In a bowl, add 6 Tbsp Saikyo miso
    (Kyoto-style white miso), 3 Tbsp mirin, and 3 Tbsp sake for the
    traditional recipe. (Optional: If you are making the optional recipe
    using 6 Tbsp white miso, add 1 Tbsp sugar.) Tip: While in some
    recipes we can replace sake with water, it's not a suitable
    substitute in this recipe due to the longer marination time
    required.

4.  Mix it all together and pour the marinade into a flat-bottomed
    airtight container.

5.  Pour 2 Tbsp sake over the fish to rinse off the salt. Gently pat dry
    with a paper towel to remove the moisture. Do not wash the fish
    under running water.

6.  Place the fish in the container and coat both sides of the fish with
    the marinade.

7.  Slather the fillets with the marinade. Cover the container and keep
    it in the refrigerator for up to 2--3 days for the traditional
    method. Tip: If you are not using Saikyo miso or regular white miso,
    you can reduce the marination time to several hours or overnight.
    Since other miso types are saltier than white miso, please adjust
    the flavor by adding more mirin or/and sugar.

[To Remove the Fish from the Marinade]{.underline}

8.  With your fingers, wipe the marinade off the fish completely. Do not
    leave any excess marinade on the fish; otherwise, it will burn
    easily. At this point, you can individually wrap the fish with
    plastic wrap and store it in a freezer bag for up to 2--3 weeks.
    Defrost in the refrigerator before cooking.

[To Prepare the Fish for Cooking]{.underline}

9.  Place the fish skin side up on a baking sheet lined with parchment
    paper/silicone mat (for baking) or aluminum foil (for broiling).

[To Bake (Recommended)]{.underline}

10. Preheat the oven to 400°F (200ºC) with a rack placed in the center
    of the oven. For a convection oven, reduce the cooking temperature
    by 25ºF (15ºC). Bake the fish on the parchment paper until the
    surface is blistered and browned a bit, about 20 minutes. You do not
    need to flip the fish. Please remember the cooking time varies
    depending on the thickness of the fish.

[To Broil (Optional)]{.underline}

11. Preheat the broiler\* with a rack placed about 8 inches (20 cm) away
    from the top heating element (in the center of the oven) for 5
    minutes. Tip: When broiling, you don't control the temperature in
    the oven; instead, you control the distance between the broiler and
    the surface of the food. It's similar to using hotter and cooler
    zones on your grill. \*There are usually three broiler settings: Low
    (450ºF/232ºC), Medium (500ºF/260ºC), and High (550ºF/288ºC). I
    usually use the Medium (6 inches away) or High (8 inches away)
    setting.

12. Place the fish on the foil-lined baking sheet and broil on High
    (550ºF/288ºC) for 8--10 minutes until the surface is blistered and
    browned a bit. Please remember the cooking time varies depending on
    the thickness of the fish and the distance between the broiler and
    the food. You do not need to flip the fish.

To Serve

13. Carefully remove the fish with a spatula and remove any burnt miso
    from the fish. Serve immediately. I serve the fish with thinly
    sliced red radishes and garnish it with a small green leaf from my
    backyard for additional color. We always eat this dish with rice.

To Store

14. You can keep the cooked leftovers in an airtight container and store
    it in the refrigerator for 3 days and in the freezer for up to a
    month.
