---
title: "Caramelized Peppers and Onions"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Vegetables"]
---

**Ingredients:**

-   2 tablespoons extra virgin olive oil

-   1 large yellow onion, peeled and sliced into ¼-inch strips

-   4 bell peppers, stemmed, seeded and cut into ¼-inch strips

-   ½ teaspoon salt

-   ½ teaspoon freshly ground black pepper

-   2 teaspoons balsamic vinegar

-   1 teaspoon fresh thyme, finely chopped (or ½ teaspoon dried thyme)

**Directions:**

1.  Heat the oil in a large skillet over medium-high heat. Add the
    onions, peppers, salt and pepper.

2.  Reduce the heat to medium-low and cook, stirring frequently, until
    the onions are caramelized and the peppers are tender and slightly
    browned, 15 to 20 minutes. If a brown coating forms on the bottom of
    the pan during the cooking process, add a few tablespoons of water
    and stir; repeat as necessary.

3.  Add balsamic vinegar and thyme and turn the heat down to low. Cook
    for a few more minutes. Taste and adjust seasoning, if necessary.
    Serve hot or at room temperature.
