---
title: "Greek Briam"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Vegetables"]
---

**Ingredients:**

-   2 pounds potatoes, peeled and thinly sliced

-   4 medium zucchini, thinly sliced

-   4 small red onions, thinly sliced

-   6 ripe tomatoes, puréed

-   ½ cup extra-virgin olive oil

-   2 tablespoons chopped fresh parsley (Optional)

-   sea salt and freshly ground black pepper to taste

**Directions:**

1.  Gather all ingredients. Preheat the oven to 400 degrees F (200
    degrees C).

2.  Spread potatoes, zucchini, and red onions in an extra-large baking
    dish (9x13-inch or larger, or 2 baking dishes).

3.  In a baking pan there are chopped red onions, zucchini, and potatoes

4.  Cover with puréed tomatoes, olive oil, and parsley; season liberally
    with sea salt and pepper. Toss until vegetables are evenly coated.

5.  Puree has been distributed evenly as well as parsley, salt and
    pepper has been added on top

6.  Bake in the preheated oven for 1 hour. Stir gently, then continue
    baking until vegetables are tender and moisture has evaporated,
    about 30 minutes more.

**Notes:**

-   Add up to 1/4 cup of water if the vegetables are too dry after the
    first hour of baking. Don\'t add too much liquid, however, as there
    should be no water left at the end of baking.
