---
title: "Roasted Red Peppers"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Vegetables"]
---

**Ingredients:**

-   Peppers

**Directions:**

1.  Preheat the oven to 450ºF\*. Line a rimmed sheet pan with parchment
    paper (for easy clean up --- make sure it extends over the edges).

2.  Meanwhile, cut peppers in half lengthwise. Remove seeds and white
    veins. Place peppers cut-side down on parchment paper.
    (Alternatively, rub a small amount of olive oil on the sheet tray.)
    Place pan in the oven for about 30 to 40 minutes, until the skin is
    blistery and charred. Don't be impatient here: If the skin isn't
    blistery enough, the peppers will be difficult to peel.

3.  Place the peppers in a large bowl and cover with plastic wrap or a
    cloth bowl cover or tea towel. Let sit for at least 20 minutes and
    up to 4 or 5 hours (or longer.) When cool enough to handle, remove
    the skin and discard.

4.  Store in an airtight container in the refrigerator until ready to
    use. You can also store the peppers with the skins still on --- I do
    this when I can't get around to peeling them right away.
