project:
  type: website

website:
  title: "Chris Kornaros"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: pages/about/about.qmd
      - text: "Guides"
        href: pages/guides/guides.qmd
      - text: "Projects"
        href: pages/projects/projects.qmd
      - text: "Blogs"
        href: pages/blogs/blogs.qmd

sidebar:
    style: floating
    collapse-level: 2
    contents:
      - id: guides
        title: "Guides"
        contents:
          - id: quarto
            title: "Quarto"
            href: /pages/guides/quarto/quarto.qmd  # Corrected to direct file
          - id: uv
            title: "uv"
            href: /pages/guides/uv/uv.qmd  # Corrected to direct file
          - href: /pages/guides/guides.qmd  # Ensure this links directly
      - id: projects
        title: "Projects"
        href: /pages/projects/projects.qmd  # Corrected to direct file
        contents:
          - id: data_engineering
            title: "Data Engineering and Architecture"
            href: /pages/projects/data_engineering/data_engineering.qmd  # Corrected to direct file
            contents:
              - id: de_datacamp
                title: "DataCamp Data Engineering Projects"
                href: /pages/projects/data_engineering/datacamp/datacamp.qmd  # Corrected to direct file
              - id: de_research
                title: "Data Engineering Research Projects"
                href: /pages/projects/data_engineering/research/research.qmd  # Corrected to direct file
          - id: data_science
            title: "Data Science and Machine Learning"
            href: /pages/projects/data_science/data_science.qmd  # Corrected to direct file
            contents:
              - id: ds_datacamp
                title: "DataCamp Data Science Projects"
                href: /pages/projects/data_science/datacamp/datacamp.qmd  # Corrected to direct file
              - id: ds_kaggle
                title: "Kaggle Projects"
                href: /pages/projects/data_science/kaggle/kaggle.qmd  # Corrected to direct file
              - id: ds_research
                title: "Research Projects"
                href: /pages/projects/data_science/research/research.qmd  # Corrected to direct file
      - id: blogs
        title: "Blogs"
        href: /pages/blogs/blogs.qmd  # Corrected to direct file
        contents:
          - id: tech_blogs
            title: "Technology Blogs"
            href: /pages/blogs/tech/tech.qmd  # Corrected to direct file
          - id: research_blogs
            title: "Research Blogs"
            href: /pages/blogs/research/research.qmd  # Corrected to direct file



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
