project:
  type: website

website:
  title: "Chris Kornaors"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - pages/about/about.qmd
      - sidebar:guides
      - sidebar:projects
      - sidebar:blogs

  sidebar:
    - id: guides
      title: "Guides"
      style: "floating"
      background: light
      collapse-level: 2
      contents: 
        - id: quarto
          title: "Quarto"
          href: pages/guides/quarto/quarto.qmd
        - id: uv
          title: "uv"
          href: pages/guides/uv/uv.qmd
        - pages/guides/guides.qmd
      
    - id: projects
      title: "Projects"
        
    - id: blogs
      title: "Blogs"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    