project:
  type: website

website:
  title: "Chris Kornaors"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - pages/about/about.qmd
      - sidebar:guides
      - sidebar:projects
      - sidebar:blogs

  sidebar:
    - id: guides
      title: "Guides"
      style: "floating"
      background: light
      collapse-level: 2
      contents: 
        - id: quarto
          title: "Quarto"
          href: pages/guides/quarto/quarto.qmd
        - id: uv
          title: "uv"
          href: pages/guides/uv/uv.qmd
        - pages/guides/guides.qmd
      
    - id: projects
      title: "Projects"
      contents:
        - id: data_engineering
          title: "Data Engineering and Architecture"
          href: pages/projects/data_engineering/data_engineering.qmd
          contents:
            - id: de_datacamp
              title: "DataCamp Data Engineering Projects"
              href: pages/projects/data_engineering/datacamp/datacamp.qmd
            - id: de_research
              title: "Data Engineering Research Projects"
              href: pages/projects/data_engineering/research/research.qmd
        
    - id: blogs
      title: "Blogs"
      contents:
        - id: tech_blogs
          title: "Technology Blogs"
          href: pages/blogs/tech/tech.qmd
        - id: research_blogs
          title: "Research Blogs"
          href: pages/blogs/research/research.qmd
        - pages/blogs/blogs.qmd


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    