project:
  type: website

website:
  title: "Chris Kornaros"
  navbar:
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: pages/about/about.qmd
      - text: "Guides"
        menu: 
          - pages/guides/guides.qmd
      - text: "Projects"
        menu:
          - pages/projects/projects.qmd
          - pages/projects/data_engineering/data_engineering.qmd
          - pages/projects/data_science/data_science.qmd
      - text: "Blogs"
        menu:
          - pages/blogs/blogs.qmd
          - pages/blogs/research/research.qmd
          - pages/blogs/tech/tech.qmd

  sidebar:
    - id: guides
      title: "Guides"
      style: "docked"
      collapse-level: 3
      contents:
        - id: guides_home
          title: "Guides"
          href: pages/guides/guides.qmd
        - id: quarto
          title: "Quarto"
          href: pages/guides/quarto/quarto.qmd
        - id: uv
          title: "uv"
          href: pages/guides/uv/uv.qmd

      
    - id: projects
      title: "Projects"
      contents:
        - title: "Projects"
          href: pages/projects/projects.qmd
        - title: "Data Engineering and Architecture"
          href: pages/projects/data_engineering/data_engineering.qmd
          contents:
            - title: "DataCamp Data Engineering Projects"
              href: pages/projects/data_engineering/datacamp/datacamp.qmd
              contents:
                - id: bank_etl
                  href: pages/projects/data_engineering/datacamp/bank_etl/bank_etl.qmd
            - title: "Data Engineering Research Projects"
              href: pages/projects/data_engineering/research/research.qmd
        - id: data_science
          title: "Data Science and Machine Learning"
          href: pages/projects/data_science/data_science.qmd
          contents:
            - title: "DataCamp Data Science Projects"
              href: pages/projects/data_science/datacamp/datacamp.qmd
              contents:
                - text: gym_market
                  href: pages/projects/data_science/datacamp/gym_market/gym_market.qmd
                - id: login_validation
                  href: pages/projects/data_science/datacamp/login_validation/login_validation.qmd
                - id: netflix
                  href: pages/projects/data_science/datacamp/netflix/netflix.qmd
            - id: ds_kaggle
              title: "Kaggle Projects"
              href: pages/projects/data_science/kaggle/kaggle.qmd
            - id: ds_research
              title: "Research Projects"
              href: pages/projects/data_science/research/research.qmd
        
    - id: blogs
      title: "Blogs"
      contents:
        - title: "Blogs"
          href: pages/blogs/blogs.qmd
        - title: "Research Blogs"
          href: pages/blogs/research/research.qmd
        - title: "Technology Blogs"
          href: pages/blogs/tech/tech.qmd
          
 