project:
  type: website

website:
  title: "ChrisKornaros"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - pages/about/about.qmd
      - pages/quarto/quarto.qmd
      - pages/repos/repos.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



