project:
  type: website

website:
  title: "Chris Kornaros"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: pages/about/about.qmd
      - text: "Guides"
        href: sidebar:section:Guides
      - text: "Projects"
        href: sidebar:projects
      - text: "Blogs"
        href: sidebar:blogs

  sidebar:
    style: docked
    background: light
    collapse-level: 2
    contents:
      - section: "Guides"
        title: "Guides"
        href: pages/guides/guides.qmd
        contents:
            - section: "Quarto"
              id: quarto
              href: pages/guides/quarto/quarto.qmd
            - section: "uv"
              id: uv
              href: pages/guides/uv/uv.qmd
      - section: "Projects"
        id: projects
        href: pages/projects/projects.qmd
        contents:
          - section: "Data Engineering and Architecture"
            id: data_engineering
            href: pages/projects/data_engineering/data_engineering.qmd
            contents:
                - section: "DataCamp Data Engineering Projects"
                  id: de_datacamp
                  href: pages/projects/data_engineering/datacamp/datacamp.qmd
                  contents:
                      - section: 
                - section:
                  id: de_research
                  href: pages/projects/data_engineering/research/research.qmd
                  contents:
                      - section:
          - section: "Data Science and Machine Learning"
            id: data_science
            href: pages/projects/data_science/data_science.qmd
            contents:
                - section: "DataCamp Data Science Projects"
                  id: ds_datacamp
                  href: pages/projects/data_science/data_science.qmd
                  contents:
                      - section:
                - section: "Kaggle Projects"
                  id: ds_kaggle
                  href: pages/projects/data_science/data_science.qmd
                  contents:
                      - section:
                - section: "Research Projects"
                  id: ds_research
                  href: pages/projects/data_science/data_science.qmd
                  contents:
                      - section: 
      - section: "Blogs"
        id: blogs
        href: pages/blogs/blogs.qmd
        contents:
            - section: "Technology Blogs"
              id: tech_blogs
              href: pages/blogs/tech/tech.qmd
              contents:
                  - title: 
            - section: "Research Blogs"
              id: research_blogs
              href: pages/blogs/research/research.qmd
              contents:
                  - title:


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
