---
title: "Marinated Sweet Peppers"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Oils and Marinades"]
---

**[Ingredients:]{.underline}**

-   4 red, yellow, or orange bell peppers, all one color or a mix

-   1/2 cup extra virgin olive oil

-   1/4 cup white wine vinegar

    -   Recipe originally called for white balsamic vinegar and ½ cup,
        but 2:1 oil:vinegar is a better ratio

    -   unseasoned rice vinegar also good options

-   1 tbsp honey

-   Italian seasoning

-   1/2 - 1 tsp crushed red pepper flakes (to taste)

-   1 tsp salt

-   1 tsp ground black pepper

-   **Not used by me:**

    -   2 cloves of garlic, peeled and minced (more if you want an
        intense garlic flavor)

    -   A couple of sprigs of fresh thyme

    -   1/2 cup of chopped fresh parsley

**[Directions:]{.underline}**

1.  To roast the peppers in the oven: Set a rack in the top third of
    your oven and preheat the broiler. Line a rimmed baking sheet with
    aluminum foil. Lay the peppers on the baking sheet and broil until
    their skins are about 90% blackened. Turn them over and broil until
    they are 90% blackened on all sides.

2.  To roast the peppers on a Blackstone Griddle: Turn the burner to
    high and allow the griddle to preheat for 10 minutes. Lay the
    peppers on the hot griddle and let them cook, undisturbed, until
    they are about 90% blackened on the bottom. Turn the peppers and
    continue to cook until they are blackened on all sides. (The peppers
    can also be roasted on a gas or charcoal grill.)

3.  Place the hot peppers in a bowl. Cover the bowl with a towel and let
    stand until cooled to room temperature.

4.  Add the remaining ingredients to a separate bowl and whisk to
    combine.

5.  Peel the blackened skins from the peppers and remove the stems and
    seeds. Slice or tear the peppers into strips that are roughly 1-inch
    thick. (I do not do this, I opt for the filet'd or butterflied
    peppers)

6.  Drop the strips of pepper into the vinaigrette and stir to coat.
    Store in a jar or other airtight container for up to 3 weeks.
    (They\'ll probably last longer, I\'m just being safe here.)

**[Notes:]{.underline}**

-   Recipe is good, go lighter on the vinegar next time and try to
    infuse the olive oil before adding the vinegar

    -   IMO, flavor should be more savory than sour/tart
