---
title: "Sun Dried Tomatoes"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Oils and Marinades"]
---

**Ingredients:**

-   12oz cherry or grape tomatoes

    -   Ideally farmer's market or GMO flavor-bomb from HEB

-   Flaky sea salt

-   Olive oil

-   *Optional*: Italian Seasoning

-   *Optional*: Red Pepper/Chili Flakes

**Directions:**

1.  Preheat the oven to 215 degrees fahrenheit (this is a bit variable
    depending on the size and quantity of tomatoes) and line a large
    baking sheet with parchment paper

2.  Halve the tomatoes and place them cut side up on the parchment paper
    (sometimes there is a bad reaction with aluminum foil according to
    the internet) and then sprinkle the flaky salt over all the tomatoes

3.  Let the tomatoes bake for \~2 hours and then check them. They should
    be pliable, but still slightly juicy at this point. Let them
    continue to go checking periodically (every 30 minutes to an hour)
    until they are dry, but still pliable.

4.  Transfer to a mason jar and cover with olive oil and any desired
    spices. They should last for up to 3 weeks in the fridge, covered in
    oil.

**Notes:**

-   Just tomatoes in oil is better for sandwiches

-   The seasoned ones seem better for salads or things where extra
    flavor is needed (probably also need higher quality spices)
