---
title: "Gumbo - Weissman"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["New Orleans"]
---

**Ingredients:**

*Stock:*

-   2 yellow onions, quartered

-   2 carrots, rough chop

-   1 lb (453.59g) crab or lobster shells

-   1 lb (453.59g) shrimp shells

-   2 lbs (900g) bone-in short rib

-   2 lbs (900g) boneless beef chuck roast

-   1 Tbsp (9g) black peppercorns

-   3 bay leaves

-   5 quarts water

-   4 thyme sprigs

*Cajun Seasoning:*

-   1.5 Tbsp (6g) garlic powder

-   2 Tbsp (17g) cayenne powder

-   2 Tbsp (12g) smoked paprika

-   2 tsp (6g) onion powder

-   1 Tbsp (6g) fresh ground black pepper

-   2 tsp (2g) dried thyme

-   1 Tbsp (2g) dried oregano

-   2 tsp (8g) MSG

-   1.5 Tbsp (11g) kosher salt

-   2 tsp (6g) ground white pepper

-   1 Tbsp (13g) dark brown sugar

*Gumbo:*

-   ½ cup (77g) duck fat

-   ½ cup (96g) lard or bacon fat

-   1 cup (150g) all-purpose flour

-   3 ribs celery, medium diced

-   2 onion, medium diced

-   1 large green bell pepper, medium diced

-   4 garlic cloves, finely chopped

-   ½ lbs (250g) andouille sausage, sliced on a bias ½" thick

-   ½ lb (250g) kielbasa sausage, sliced on a bias ½" thick

-   2.5 Tbsp (35g) cajun seasoning

-   3 Tbsp (41g) Louisiana hot sauce

-   3.25 quarts (3 L) stock

-   20 oz (750g) canned crushed fire-roasted tomatoes

-   2.5 tsp (4g) filé powder - first measurement

-   2 clusters snow king crab legs

-   3 snow crab clusters

-   1 lb uncooked shrimp, peeled and deveined

-   4 lobster tails, raw and deveined

-   2.5 tsp (4g) filé powder - second measurement

-   3 Tbsp (40g) Worcestershire sauce

-   Kosher salt to taste

-   1 cup cooked rice

*MSG Butter:*

-   1 cup (226g) salted butter, softened

<!-- -->

-   1.5 tsp (6g) of MSG

-   4 cloves grated garlic

-   2 Tbsp thinly sliced chives

**Directions:**

*Stock:*

1.  De-shell the lobster by cutting along the underside with kitchen
    shears, cracking the sides, and gently pulling out the meat. Set the
    meat and shell aside separately.

2.  Break down 3 snow crab clusters, reserve the meat, and place the
    shells with the rest of the stock ingredients.

3.  In a big pot over medium-high, add enough oil to coat the bottom,
    add the short rib and the chuck roast searing on all sides, for 2 -
    3 minutes or until caramelized.

4.  Add in all the shellfish shells, along with the vegetables, black
    peppercorns, and bay leaves. Next, add the water, bring it to a
    boil, reduce to low heat, and simmer, skimming off any scum that
    rises to the top, and let it cook for 5 - 6 hours.

5.  Remove the solids, strain through a fine-mesh sieve.

6.  Reserve.

*Cajun Seasoning:*

1.  Mix all ingredients.

*The Gumbo:*

1.  In a large stockpot (10 quarts), add the duck fat, pork fat, heat
    over medium heat; once it's melted, add the flour, mix it, and let
    it cook, occasionally stirring until a dark mahogany color, around
    15 minutes.

2.  Cut both sausages on a half an inch piece on a bias. Reserve.

3.  Add the celery, onion, and bell pepper to the pot, sauté until soft,
    add the garlic, sauté until fragrant, then add the sausages and let
    it rend some of the fat.

4.  Add the Cajun seasoning, let it toast for one minute, then add the
    Louisiana hot sauce, beef stock, tomatoes, and bring it to a boil,
    lower the heat to medium-low, and simmer for one hour.

5.  Add the filet powder (first measurement), simmer for 25 minutes, add
    the bottom segment from two snow crab clusters, remove the meat from
    the rest of the clusters, and place it to the side.

6.  Add three whole snow crab clusters, broken into individual pieces,
    then add the shrimp, the devein lobster (one-inch chunks). Lower the
    heat to low, simmer for 15 minutes.

7.  Add file powder (second measurement), and simmer for 5 minutes. Then
    add all of the king crab meat and the Worcestershire sauce.

8.  Once the meat is hot, it is ready to serve.

*MSG Butter:*

1.  Combine the butter, msg, garlic, chives, mix it and fold together
    until thoroughly combined.

2.  On a sheet of plastic wrap, spread the butter into a seven-inch long
    strip, roll the plastic wrap around it, fully enclosing the butter,
    then grab the two sides and let it roll and wind up into a sausage
    and place it in the fridge until solid.

3.  Slice a medallion and place it in your bowl of gumbo.

**Source:**
[[https://www.joshuaweissman.com/recipes/homemade-gumbo-recipe-with-creole-butter]{.underline}](https://www.joshuaweissman.com/recipes/homemade-gumbo-recipe-with-creole-butter)
