---
title: "Jambalaya"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["New Orleans"]
---

**Ingredients:**

-   1 tablespoon olive oil or butter

-   ¼ pound salt pork, chopped into 1-inch cubes (or substitute cooked
    ham or bacon)

-   ½ pound andouille sausage, sliced ½ inch thick (or substitute
    another smoked sausage such as kielbasa or chorizo)

-   ½ pound hot Italian sausage, sliced ½ inch thick (or substitute
    another spicy, uncooked sausage)

-   ½ pound boneless skinless chicken breasts, chopped into 1-inch cubes

-   1 onion, minced

-   1 green bell pepper, seeded and minced

-   2 stalks celery, minced

-   3 cups long-grain rice

-   ½ teaspoon paprika

-   1 tablespoon fresh parsley leaves

-   1 teaspoon fresh thyme leaves

-   1 jalapeño, seeded and minced

-   2 cloves garlic, minced

-   1 tablespoon kosher salt, plus more to taste

-   ½ teaspoon freshly ground black pepper

-   1 teaspoon cayenne pepper or hot sauce, plus more to taste

-   2 bay leaves

-   1 teaspoon dried oregano

-   1 pound shrimp, peeled and deveined

-   4 cups homemade chicken stock or low-sodium chicken broth

-   2 green onions, thinly sliced on the diagonal

**Directions:**

1.  Heat oil in a Dutch oven, large pot, or very large skillet
    (preferably cast iron) over medium heat. Add pork, sausage, and
    chicken breast. Sauté meat until lightly browned and fat has
    rendered out, about 5--10 minutes.

2.  Once fat has rendered, add onion, bell pepper, and celery, and
    cover, stirring occasionally until softened and fragrant, about
    5--10 more minutes. Add rice and stir to coat.

3.  Add remaining ingredients except the green onions, and increase heat
    to medium-high heat. Bring to a boil and let boil for 5 minutes.
    Reduce heat to low, cover, and simmer until rice is tender and
    liquid is fully absorbed, about 25--30 minutes. If necessary, add
    water to prevent drying out. Taste and adjust seasoning.

4.  Fluff with a fork, garnish with green onions, and serve warm with
    hot sauce.

**Source:**
[[https://www.masterclass.com/articles/how-to-make-jambalaya]{.underline}](https://www.masterclass.com/articles/how-to-make-jambalaya)
