---
title: "NYT_ Steak and Salsa Verde"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Beef"]
---

**Ingredients: (**Yield: 4 servings)

-   1½pounds skirt steak

-   ½cup extra-virgin olive oil

-   ¼cup red-wine vinegar

-   ¼cup thinly sliced scallions (about 2)

-   2tablespoons capers, drained and roughly chopped

-   1tablespoon minced garlic (about 2 large cloves)

-   ½teaspoon kosher salt, plus more to taste

-   ½teaspoon black pepper, plus more to taste

-   2tablespoons chopped fresh flat-leaf parsley

-   2tablespoons chopped fresh mint

-   ¼cup toasted pine nuts

**Step 1**\
If necessary, cut the steak crosswise into large pieces that will fit
into a shallow, nonreactive dish. Transfer the steaks to the dish. In a
glass measuring cup or bowl, whisk together the olive oil, vinegar,
scallions, capers, garlic, ½ teaspoon salt and ½ teaspoon pepper. Pour
about ⅓ of the dressing (about ⅓ cup) over the steak and turn to coat
both sides.

**Step 2**\
Add the parsley and 1 tablespoon mint to the reserved dressing, stir,
and set aside until ready to use. Cover and refrigerate the steak for at
least 30 minutes or up to 24 hours. (If marinating the steak overnight,
cover and refrigerate the reserved dressing.)

**Step 3**\
In a small sauté pan set over medium heat, toast the pine nuts, tossing
often, until golden brown, about 3 minutes. Set aside.

**Step 4**\
Set the grill to medium-high heat, or heat a grill pan on the stovetop
over medium-high. Pat the steaks dry with a paper towel and grill for 3
to 5 minutes on each side for medium-rare. Transfer to a plate, sprinkle
with salt, and allow to rest for 10 minutes.

**Source:**
[[https://cooking.nytimes.com/recipes/1020355-skirt-steak-with-salsa-verde-salad]{.underline}](https://cooking.nytimes.com/recipes/1020355-skirt-steak-with-salsa-verde-salad)
