---
title: "Basic Ficelle Recipe"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Baked Goods"]
---

**Ingredients:**

-   3 cups (410 grams) all-purpose flour (or bread flour)

-   3-4 cup (200 grams) room-temperature water

-   1 tsp (4 grams) instant yeast

-   1 tsp (7 grams) salt

-   1 tsp (5 grams) sugar

**Directions:**

1.  **Knead the dough:** In the bowl of stand mixer, add water, flour,
    salt, sugar and yeast. Attach the dough hook, turn on the mixer and
    knead the dough on low speed for 6 minutes, then increase to medium
    speed and knead for another 6 minutes. **(the dough should be dry at
    this stage).**

2.  Roll the dough into a ball and let it rest for 15 minutes. Next,
    divide the ball into 6 equal pieces and let it rest for another 15
    minutes to make it easier to shape.

3.  **Shape the ficelle:** shape each ball into a ficelle shape, about
    17 inch longer (45cm) **(See above for how to shape a ficelle
    step-by-step)**. Place the dough on a baking sheet lined with
    parchment paper. **(If your baking sheet is only 18 inches long or
    less, you can use two baking sheets and place the ficelle dough at a
    45-degree angle).**

4.  **Rise:** Put a bowl filled with boiling water in the bottom of the
    oven to create a warm, humid environment. Then, place the baking
    sheet in the oven and allow the dough to rise for one hour. **(80
    degrees Fahrenheit (28 degrees Celsius) is best for the dough to
    rise).**

5.  Remove your baking sheet and let the boiling water. Preheat your
    oven at 440 degrees Fahrenheit (230 degrees Celsius).

6.  Score the ficelle dough with a sharp knife and spray them with
    water.

7.  **Bake the ficelle:** Remove the bowl of the boiling water and place
    the baking sheet in the oven. Bake the ficelle for 15 minutes or
    until golden brown on the top. When they are hot, spray them with
    water.
