---
title: "Pita"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Baked Goods"]
---

**Ingredients:**

-   1 cup lukewarm water

-   2 tsp active dry yeast

-   1/2 tsp sugar

-   3 cups all-purpose flour, divided (or 1 1/2 cup all-purpose flour
    and 1 1/2 cup whole wheat flour)

-   1 to 2 tsp kosher salt (I used Diamond Crystal kosher salt)

-   2 tbsp extra virgin olive oil (I used [[Private
    Reserve]{.underline}](https://shop.themediterraneandish.com/product/private-reserve-extra-virgin-olive-oil/)
    Greek extra virgin olive oil), more for the bowl

**Directions:**

1.  **Make sponge:** In a large mixing bowl add the lukewarm water and
    stir in yeast and sugar until dissolved. Add 1/2 cup flour and whisk
    together. Place the mixing bowl in a warm place, uncovered to form a
    lose sponge. Give it 15 minutes or so, the mixture should bubble.

2.  **Form the pita dough:** Now add salt, olive oil and almost all the
    remaining flour (keep about 1/2 cup of the flour for dusting later).
    Stir until mixture forms a shaggy mass (at this point, the dough has
    little to no gluten development and just looks like a sticky mess
    and you can easily pull bits off). Dust with a little flour, then
    knead the mixture inside the bowl for about a minute to incorporate
    any stray bits.

3.  **Knead the dough:** Dust a clean working surface with just a little
    bit of flour. Knead lightly for a couple minutes or so until smooth.
    Cover and let the dough rest for 10 minutes, then knead again for a
    couple more minutes. The dough should be a little bit moist, you can
    help it with a little dusting of flour, but be careful not to add
    too much flour.

4.  **Let the dough rise.** Clean the mixing bowl and coat it lightly
    with extra virgin olive oil and put the dough back in the bowl. Turn
    the dough a couple times in the bowl to coat with the olive oil.
    Cover the mixing bowl tightly with plastic wrap then lay a kitchen
    towel over. Put the bowl in a warm place. Leave it alone for 1 hour
    or until the dough rises to double its size.

5.  **Divide the dough.** Deflate the dough and place it on a clean work
    surface. Divide the dough into 7 to 8 equal pieces and shape them
    into balls. Cover with a towel and leave them for 10 minutes or so
    to rest.

6.  **Shape the pitas.** Using a floured rolling pin, roll one of the
    pieces into a circle that's 8-9 inches wide and about a quarter inch
    thick. It helps to lift and turn the dough frequently as you roll so
    that dough doesn't stick to your counter too much. (If dough starts
    to stick, sprinkle a tiny bit of flour). If the dough starts to
    spring back, set it aside to rest for a few minutes, then continue
    rolling. Repeat with the other pieces of dough. (Once you get going,
    you can be cooking one pita while rolling another, if you like). You
    have two options for baking the pita from here.

7.  **To bake pita in the oven:** Heat the oven to 475 degrees F and
    place a heavy-duty baking pan or large cast iron skillet on the
    middle rack to heat. Working in batches, place the rolled-out pitas
    directly on the hot baking baking sheet (I was only able to fit 2 at
    a time). Bake for 2 minutes on one side, and then, using a pair of
    tongs, carefully turn pita over to bake for 1 minute on the other
    side. The pita will puff nicely and should be ready. Remove from the
    oven and cover the baked pitas with a clean towel while you work on
    the rest of the pitas.

8.  **To cook pita on stovetop:** Heat a cast iron skillet over
    medium-high heat. (Test by adding a couple drops of water to the
    skillet, the skillet is ready when the beads of water sizzle
    immediately). Drizzle a tiny bit of extra virgin olive oil and wipe
    off any excess. Working with one pita at a time, lay a rolled-out
    pita on the skillet and bake for 30 seconds, until bubbles start to
    form. Using a spatula, flip the pita over and cook for 1-2 minutes
    on the other side, until large toasted spots appear on the
    underside. Flip again and cook another 1-2 minutes to toast the
    other side. The pita is ready when it puffs up forming a pocket
    (sometimes, with this method, the pita may not puff or may only form
    a small pocket. Try pressing the surface of the pita gently with a
    clean towel). Keep baked pita covered with a clean towel while you
    work on the rest.

Source:
[[https://www.themediterraneandish.com/homemade-pita-bread-recipe/#tasty-recipes-10391-jump-target]{.underline}](https://www.themediterraneandish.com/homemade-pita-bread-recipe/#tasty-recipes-10391-jump-target)
