---
title: "Richard Bertinet Baguette"
author: "Chris Kornaros"
date: 2026-03-06
categories: ["Baked Goods"]
---

**Ingredients:**

-   35 oz / 1000g bread flour (strong)

-   0.7 oz / 20g Fresh yeast

    -   0.35 oz / 10g if using *dry instant yeast*

-   24.5 fl oz / 700g Water

-   0.7 oz / 20g Salt

**Directions:**

1.  Pour water into a stand mixer bowl, then add flour. Rub yeast in
    hands with a bit of flour into the bowl. Keep the salt to the side
    for now.

2.  Turn mixer on, slow speed for 4 minutes (2 if using half the
    ingredients). Then, slowly add the salt, and let the mixer go for
    another 4 minutes (2 if using half the ingredients).

3.  Turn the dough out (releasing it from the sides of the bowl first
    helps), **[do not]{.underline}** add a lot of flour to your surface.
    "Take the dough for a walk." Keep the top of the dough facing
    upwards, then using a dough scraper rotate the dough and move it
    around-- keeping the top upright the whole time.

4.  Now dough won't be sticky on top, lightly dust with flour, dust a
    bowl with flour, then rest the dough in a bowl, covered with a towel
    for an hour. Next, rest it overnight in the fridge covered with a
    plastic bag and towel. The plastic bag prevents that hard crust like
    texture from building up on the raw dough, keeps it moist.

5.  First, put some flour down on your board. Using your scraper,
    release the dough.Turn the bowl upside down and just dump it out, so
    the bottom of the bowl is facing up. Using the scraper, separate out
    5.30 oz / 150g (6-12 depending on recipe scale) portions of the
    dough-- you don't want them too big. Try to be precise, any extra
    bits of dough should be cut off and put on top of the rectangular
    piece on the scale (if you need to add weight).

6.  Before you shape, clear the flour away, you don't want that going
    everywhere and getting inside the dough. Lay out one of the
    rectangular portions (remember to keep the extra bit on top, if
    there is any). Then, press your fingers into the middle, making a
    dent / spine. Now, fold the top half (above the spine) of the dough
    towards you, pressing the edge down into the spine with your
    fingers, to seal the dough. Finally, take the top right edge of the
    dough and fold it over towards the bottom right edge, pinching down
    with your thumb/palm to seal it-- continue along the length of the
    dough until done.

7.  To roll the dough into the baguette shape. Put your hands on the
    edges, away from the middle, then push hard and roll the dough out
    and back, three times. Then, place the shaped loaf onto your linen /
    shaping cloth. Leave your loaves on the cloth, covered with another
    towel for 20 minutes to proof. While you are waiting, preheat your
    oven to 450 degrees fahrenheit, with a cast iron skillet on the
    bottom-- you can use a baking dish if you don't have a skillet... BE
    CAREFUL OF THERMAL SHOCK IF DOING THIS (don't use pyrex it will
    explode)

8.  Transfer your loaves to a paddle (if you have one), make sure to
    dust with a bit of semolina or flour on the bottom so they don't
    stick (if doing this part, sometimes I just go straight to the pan
    and score there). Dust the tops with some flour. Then, do 2-3 long
    vertical cuts with a bread lame. Make sure to keep the lame at a 45
    degree angle, but cutting straight towards yourself (not on the
    sides or diagonally along the loaf). This lets you control where the
    gas escapes to when baking. If you don't score the bread, it just
    escapes in the weakest part of the dough-- which is how you end up
    with the side of a loaf blown open. Once scored, place your loaf (or
    loaves if multiple) onto the baking sheet and prepare to bake.

9.  Make sure the oven is at 450-475 F (test this), put your sheet with
    the loaves onto the middle rack-- if using a baking stone, just
    directly slide the raw loaves onto that using your wooden peel.Then,
    pour boiling water into the cast iron skillet (adding several large
    ice cubes works as well) and quickly shut the door. This creates a
    moist, steamy environment which helps with the crust and aeration
    during the bake.

10. If you are batch prepping loaves, you can stop at about 5-7 minutes
    into the bake and pull the loaves. Parbaking until here lets you
    freeze these and bake them later, while maintaining the freshness
    and texture. The crust should have started to form on the top and
    bottom already. Simply take them out and freeze them. Later, defrost
    the baguette and then finish baking it before enjoying.

**Notes:**

-   It seems 20-23 minutes at 425\~ works for par baking as well

-   Adding the salt while it's going ended up with the best dough I've
    had yet

-   Make sure to release the dough, then dump it upside down when
    beginning the shaping

-   

**Source:**
[[https://www.youtube.com/watch?v=8clAqfrk-pk]{.underline}](https://www.youtube.com/watch?v=8clAqfrk-pk)

[[https://www.gozney.com/blogs/recipes/french-baguettes-recipe?fromsocial=true]{.underline}](https://www.gozney.com/blogs/recipes/french-baguettes-recipe?fromsocial=true)
