name: Publish Website

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.6.40'  # Adjust to your Quarto version
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          # Install a specific version of uv.
          version: "0.7.3"

      - name: Install Python
        run: uv python install
      
      - name: Install the uv project
        run: uv sync
      
      - name: Render Quarto Website
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: source

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs